### ISSUE TITLE
What about add `ssd_mobilenet` of google

### ISSUE THREAD

**Issue by GarrickLin** [zhreshold/mxnet-ssd#101]
Google recently open sourced [mobilenet](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md) of object detection as is known. Will you plane to add `mobilenet` as its fast speed and fine performance?

**Comment by chinakook** [comment]
+1

**Comment by zhreshold** [comment]
Please wait until a faster kernel for depth-wise convolution is merge into mxnet. Otherwise training a mobilenet is quite time consuming.

**Comment by chinakook** [comment]
https://github.com/apache/incubator-mxnet/commit/d7d31b2d9ce2eee98a3b9f41bc8c526a3125ce78
@zhreshold ,It's merged.

**Comment by zhreshold** [comment]
I see, will try it out.

**Comment by chinakook** [comment]
I've tried mobilenet a few days. I have some experiences as follow:
1. I fork the network config from 'resnet50'(symbol_factory.py)
2. I used the pretrain model from (https://github.com/KeyKy/mobilenet-mxnet), this model need scale the color space with 0.017.The mean value is same to VGG16_reduced.
3. I've set the lr_mult of bn to 0.1
4. sgd optimizer can not get convergent well, but RMSProp with wd = 0.00005 is all OK.(https://github.com/chuanqi305/MobileNet-SSD)
5. The mobilenet-ssd performance on GPU is worse than VGG-ssd, but CPU performance is far better.
That's all changes, may these can help you.

**Comment by xhzcyc** [comment]
What about the mAP using mobilenet? @chinakook

**Comment by chinakook** [comment]
@xhzcyc I've not train VOC yet, but I train my own data and the result is same with VGG16-reduced.

**Comment by zhreshold** [comment]
It's available now.

**Comment by GarrickLin** [comment]
did you use a pretrained mobilenet model or just from scratch?

**Comment by GarrickLin** [comment]
I have trained a 512x512 mobilenet at mAP=70.61% from scratch. Is this resonable ?

**Comment by zhreshold** [comment]
@GarrickLin I'm training from retrained model. So if you can get > 70 from scratch, which is good news.

**Comment by GarrickLin** [comment]
Did you pretrain the model yourself ? I didn't find the official release of mobilenet in gluon. By the way, I am training SSD using gluon now. It due to your work, thanks.
