### ISSUE TITLE
Can you provide pretrained inceptionv3 model?

### ISSUE THREAD

**Issue by zt706** [zhreshold/mxnet-ssd#105]
Hi zhreshold:
    Can you provide pretrained inceptionv3 model? You use the inceptionv3 is not http://mxnet.io/model_zoo/ here inceptionv3?

**Comment by edmBernard** [comment]
some mxnet pretrained model are here : https://github.com/dmlc/mxnet-model-gallery

**Comment by zhreshold** [comment]
The inception v3 I used is a legacy model, might be slightly different from the one in model-zoo,
but what's the point to get a new one?

**Comment by zt706** [comment]
The model of inccetionv3 does not converge. I confirm that the data is good because I used the vgg16 pre-training model you provided to train is convergent.

my train cmd: 
```bash
python train.py --gpus 4,5,6,7 --batch-size 32 --pretrained ./model/pretrain_model/Inception-BN 
--epoch 126 --prefix './model/new_train_model/inceptionv3/ssd' --network inceptionv3  --data-shape 512
```

the train log:
INFO:root:Epoch[88] Batch [460] Speed: 32.25 samples/sec        CrossEntropy=0.718335   SmoothL1=0.323405
INFO:root:Epoch[88] Batch [480] Speed: 32.15 samples/sec        CrossEntropy=0.751861   SmoothL1=0.337154
INFO:root:Epoch[88] Batch [500] Speed: 32.25 samples/sec        CrossEntropy=0.759293   SmoothL1=0.331747
INFO:root:Epoch[88] Train-CrossEntropy=0.734820
INFO:root:Epoch[88] Train-SmoothL1=0.333367
INFO:root:Epoch[88] Time cost=515.692
INFO:root:Saved checkpoint to "./model/new_train_model/inceptionv3/ssd_inceptionv3_512-0089.params"
INFO:root:Epoch[88] Validation-aeroplane=0.090909
INFO:root:Epoch[88] Validation-bicycle=0.000000
INFO:root:Epoch[88] Validation-bird=0.000000
INFO:root:Epoch[88] Validation-boat=0.000525
INFO:root:Epoch[88] Validation-bottle=0.000193
INFO:root:Epoch[88] Validation-bus=0.000000
INFO:root:Epoch[88] Validation-car=0.090909
INFO:root:Epoch[88] Validation-cat=0.000000
INFO:root:Epoch[88] Validation-chair=0.001868
INFO:root:Epoch[88] Validation-cow=0.000000
INFO:root:Epoch[88] Validation-diningtable=0.004070
INFO:root:Epoch[88] Validation-dog=0.000018
INFO:root:Epoch[88] Validation-horse=0.000000
INFO:root:Epoch[88] Validation-motorbike=0.000000
INFO:root:Epoch[88] Validation-person=0.002549
INFO:root:Epoch[88] Validation-pottedplant=0.000980
INFO:root:Epoch[88] Validation-sheep=0.000312
INFO:root:Epoch[88] Validation-sofa=0.047703
INFO:root:Epoch[88] Validation-train=0.000000
INFO:root:Epoch[88] Validation-tvmonitor=0.091883
INFO:root:Epoch[88] Validation-mAP=0.016596

**Comment by zhreshold** [comment]
@zt706 You are using Inception-BN pretrained model, Inception-v3 should be used.

**Comment by zt706** [comment]
-_-!! thank you vvvery much.
