### ISSUE TITLE
The compability with python 3.6.1 is really bad

### ISSUE THREAD

**Issue by chinakook** [zhreshold/mxnet-ssd#109]
I cannot run any python script normally in python 3.6.1 env.

**Comment by edmBernard** [comment]
What error did you have ?

**Comment by chinakook** [comment]
1. from common import multi_layer_feature, multibox_layer
2. import symbol_builder

**Comment by edmBernard** [comment]
Have you update mxnet-ssd code recently ? 
There was PR for python3 compatibility that fix almost all this import error 20 days ago.
https://github.com/zhreshold/mxnet-ssd/pull/104
https://github.com/zhreshold/mxnet-ssd/pull/99

**Comment by chinakook** [comment]
@edmBernard Thanks, very much! I've used the mxnet included version and I will try this soon.
