### ISSUE TITLE
mx.symbol.Scale not found

### ISSUE THREAD

**Issue by Jiakui** [zhreshold/mxnet-ssd#11]
python train.py 
Traceback (most recent call last):
  File "train.py", line 80, in <module>
    args.lr_refactor_ratio, args.monitor, args.log_file)
  File "/home/veilytech/DeepLearning2/mxnet-ssd/train/train_net.py", line 194, in train_net
    net = importlib.import_module("symbol_" + net).get_symbol_train(imdb.num_classes)
  File "/home/veilytech/DeepLearning2/mxnet-ssd/config/../symbol/symbol_vgg16_reduced.py", line 118, in get_symbol_train
    clip=True, interm_layer=0)
  File "/home/veilytech/DeepLearning2/mxnet-ssd/config/../symbol/common.py", line 111, in multibox_layer
    from_layer = mx.symbol.Scale(data=from_layer, mode="spatial", \
AttributeError: 'module' object has no attribute 'Scale'

How should I fix this problem? Thanks

**Comment by Jiakui** [comment]
I found the problem, I used the standard mxnet instead of your version.

**Comment by Jiakui** [comment]
My question is, how should I run the demo.py if I don't install your fork of mxnet? I have installed the dmlc version of mxnet  and it dosen't have the  mx.symbol.Scale module.

**Comment by zhreshold** [comment]
The extra layers are required.
But you don't necessary to install mxnet globally, use per-project mxnet is a better practice IMO.

**Comment by xhniu** [comment]
@zhreshold Sorry, i encounter this question too. How to fix it? I just finish all the operation as the github readme, how can i modify my mxnet project to run the demo.py, thank you.

**Comment by zhreshold** [comment]
@xhniu If you followed all steps correctly, and still got this error, you should check if you have installed an official repo globally. If true, import mxnet will import that one first.
Two options
1. Remove the mxnet-xxx.egg in your python global packages
2. in tools/find_mxnet, insert path before import mxnet, e.g. 
```
sys.path.insert(0, '../mxnet/python')
try:
  import mxnet as mx
...
```

**Comment by Walid-Ahmed** [comment]
@zhreshold  @Jiakui 
I tried option 2 and When I try to execute demo.py I got the same error message  
AttributeError: 'module' object has no attribute 'Scale' , 

```
import sys
sys.path.insert(0, '../mxnet/python')
try:
    import mxnet as mx
```

I had MXNET successfully installed using  instructions  from http://mxnet.io/get_started/osx_setup.html#install-the-mxnet-package-for-python

Thanks
