### ISSUE TITLE
Failed to transfer caffe's prototxt .

### ISSUE THREAD

**Issue by nopattern** [zhreshold/mxnet-ssd#12]
Thank you for good job! 
      I have used  mxnet-ssd\mxnet\tools\caffe_converter to convert  caffe's ssd300  deploy.prototxt to  mxnet's json file. The output is:
     google.protobuf.text_format.ParseError: 758:3 : Message type caffe.LayerParameter has no field named norm_param.

      Do I use it correctly?

**Comment by zhreshold** [comment]
You cannot convert caffe model directly. 
Caffe-ssd has non-official caffe layers, my impl has non-official mxnet layers, thus conversion could be cumbersome using mxnet converter.

**Comment by nopattern** [comment]
Thank you again. I will try to make a converter.
