### ISSUE TITLE
mxnet 0.11 not work

### ISSUE THREAD

**Issue by jinfagang** [zhreshold/mxnet-ssd#125]
this repo can not work at all on mxnet 0.11 ：
```
 python demo.py --gpu 0
Traceback (most recent call last):
  File "demo.py", line 152, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 56, in get_detector
    force_nms=force_nms, nms_topk=nms_topk)
  File "/home/gqx/work/frameworks/mxnet/example/ssd/symbol/symbol_factory.py", line 139, in get_symbol
    return symbol_builder.get_symbol(**config)
  File "/home/gqx/work/frameworks/mxnet/example/ssd/symbol/symbol_builder.py", line 176, in get_symbol
    num_channels=num_filters, clip=False, interm_layer=0, steps=steps)
  File "/home/gqx/work/frameworks/mxnet/example/ssd/symbol/common.py", line 286, in multibox_layer
    anchors = mx.symbol.contrib.MultiBoxPrior(from_layer, sizes=size_str, ratios=ratio_str,
AttributeError: 'module' object has no attribute 'contrib'

```
Anyidea or support would be very appreciated.

**Comment by edmBernard** [comment]
This repository use this fork of Mxnet https://github.com/zhreshold/mxnet/tree/63ac7932688a3e479006cbb0eafed59d4c6ad137
If you want to try ssd with regular Mxnet you can use this one https://github.com/apache/incubator-mxnet/tree/master/example/ssd developped by @zhreshold too

**Comment by zhreshold** [comment]
Update mxnet will fix it.

**Comment by jinfagang** [comment]
@zhreshold I am already the newest version 0.12

**Comment by zhreshold** [comment]
@jinfagang You are messing up with the mxnet path I think, try debug where the mxnet is installed and called.
```
python -c "import mxnet; print(mxnet); print(mxnet.__version__)"
```

**Comment by jinfagang** [comment]
I can exactly import and run mxnet. it just said `'module' object has no attribute 'contrib'`, this code: `mx.symbol.contrib.MultiBoxPrior` maybe out of date?
