### ISSUE TITLE
How to fine-tune using my own dataset (very few)?

### ISSUE THREAD

**Issue by ibunny01** [zhreshold/mxnet-ssd#137]
Hi, I have format my dataset (2k pics with annotations) into VOC format. And I have changed the `classes` in `pascal_voc.py`, then what should I do if I want to fine-tune using network `resnet50_ssd_512_voc0712_trainval`? 
Can anybody give me a specific command? Actually I have no idea about the arg `--finetune` and `--pretrained`, what are they supposed to be here?

**Comment by Rizhiy** [comment]
What command options did you use to solve this?
