### ISSUE TITLE
Cann't get the model named ssd_resnet50_0712.zip and vgg16_reduced model

### ISSUE THREAD

**Issue by imistyrain** [zhreshold/mxnet-ssd#139]
the utrl https://github.com/zhreshold/mxnet-ssd/releases/download/v0.6/resnet50_ssd_512_voc0712_trainval.zip is not accessable recently,
would you like to share them on other address such as Baidu yun?

**Comment by zhreshold** [comment]
It's hosted on GitHub, you may have problem accessing it due to some reason. Retry multiple times, or refer to some techniques to access GitHub first.

**Comment by hezrein** [comment]
could you share resnet50_ssd_512_voc0712_trainval.zip on Baidu yun @imistyrain ,thx
