### ISSUE TITLE
train of ssd 500  

### ISSUE THREAD

**Issue by nopattern** [zhreshold/mxnet-ssd#14]
@zhreshold 
I have tested  training of ssd 300 by  command : 
              python train.py --gpus 0,1,2,3 --batch-size 128 --lr 0.0005.
Then I used command : 
              python train.py --gpus 0,1,2,3 --batch-size 128 --lr 0.0005 --data-shape 500. 
It aslo worked. 
     But the original ssd500 is different from ssd300. Can I train ssd500 by this command?

**Comment by zhreshold** [comment]
The anchor box scale should be carefully designed according to network input size. Simply scaling to 500x500 could still work, but won't produce best results I guess.

**Comment by nopattern** [comment]
Thank you .
