### ISSUE TITLE
How to modify a model to train it on 22 classes ?

### ISSUE THREAD

**Issue by Ferbach** [zhreshold/mxnet-ssd#149]
Hello,

Thank you and congratulation for your work.

I run different model such as vgg16_reduced, Resnet50 and Inceptionv3 on the Pascal VOC dataset.
It works fine but now I would like to train my model in more than 20 classes.

So I collected some data, I made annotations and created the record file.

Then I used vgg16_reduced and it works quite well. I would like to test with Resnet50 and Inceptionv3 to make a comparison but both doesn’t work.

I know that both model was pertained using Pascal VOC on 20 classes but are their a way to train it on 22 classes ?

I don’t understand why it works in vgg16_reduced in fact because for my it should be the same problem than other models pertained on 20 classes ?

In the case of Resnet50 and Inceptionv3 I have an exception that say that it expected a vector of 84 but has a vector of 92.

I presume it is because I add two more classes so we have 2*4 parameters added at the output (the coordinates x, y and the height and wight of the bounding box)

Can I change the architecture of the model to accept 22 classes without train from scratch or use finetune ? 

Thank a lot for any help !

The command : 

python train.py --num-class 22 --class-names ./dataset/names/pascal_voc_22_classes.names --network resnet50 --pretrained ./model/resnet50 --end-epoch 300 --batch-size 32

The output :

INFO:root:Start training with (gpu(0)) from pretrained model ./model/resnet50
[09:13:28] g:\deeplearn\mxnet\src\operator\./cudnn_algoreg-inl.h:106: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[09:13:46] G:\deeplearn\mxnet\dmlc-core\include\dmlc/logging.h:308: [09:13:46] g:\deeplearn\mxnet\src\operator\tensor\../elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected (84,), got (92,)
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    voc07_metric=args.use_voc07_metric)
  File "C:\Users\aferbach\Documents\ALAN\python\image\mxnet-ssd\train\train_net.py", line 268, in train_net
    monitor=monitor)
  File "C:\Users\aferbach\AppData\Local\Continuum\miniconda3\envs\mxnet\lib\site-packages\mxnet\module\base_module.py", line 464, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "C:\Users\aferbach\AppData\Local\Continuum\miniconda3\envs\mxnet\lib\site-packages\mxnet\module\module.py", line 296, in init_params
    _impl(desc, arr, arg_params)
  File "C:\Users\aferbach\AppData\Local\Continuum\miniconda3\envs\mxnet\lib\site-packages\mxnet\module\module.py", line 284, in _impl
    cache_arr.copyto(arr)
  File "C:\Users\aferbach\AppData\Local\Continuum\miniconda3\envs\mxnet\lib\site-packages\mxnet\ndarray\ndarray.py", line 1635, in copyto
    return _internal._copyto(self, out=other)
  File "<string>", line 25, in _copyto
  File "C:\Users\aferbach\AppData\Local\Continuum\miniconda3\envs\mxnet\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Users\aferbach\AppData\Local\Continuum\miniconda3\envs\mxnet\lib\site-packages\mxnet\base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:13:46] g:\deeplearn\mxnet\src\operator\tensor\../elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected (84,), got (92,)

**Comment by zhreshold** [comment]
Finetune is available as --finetune option, please check it out.

**Comment by Ferbach** [comment]
Yes, I already try with finetune, it works but I don’t have good result in the two classes that I added. 
I would like to keep the fact that we can update the weights in the convolutional part of the network so it why I would like to avoid use finetune.

**Comment by zhreshold** [comment]
Then remove freeze parameters. Otherwise you have to strip the convolution layers for 20 classes(21 channels * num_anchor) and replace with 22(23 * num_anchors channels) classes.

**Comment by Ferbach** [comment]
Thank you for the answer, I changed the code to avoid freeze parameters in the CNN. My computer is still computing now, I hope I will have good result. If it is not the case I will try your second advice 
Thank you again !

**Comment by Ferbach** [comment]
I have good result when I force all CNN parameters to not be frozen,.
In fact I just force "fixed_param_names" to be equal to None in train_net.py

**Comment by Rizhiy** [comment]
@Ferbach What parameters did you use with finetune? I added `--finetune 0`, but it still gives me error.

**Comment by Ferbach** [comment]
It depends, for exemple I worked with finetune 215 when I was using inceptionv3 which was pretrained during 215 epochs if I remember correctly.

You can also use finetune 1 and rename the file .params to succeed.
Show me your error logs if you want

**Comment by Rizhiy** [comment]
What do you mean by finetune 215? I want to use a model trained on one dataset as a starting point for training on my dataset.

For example, starting with mobilenet provided in README, how do I use that as a starting point for training on my dataset?

**Comment by Ferbach** [comment]
I used 215 for example because if you take the model inceptionv3 in the README you have a model which was pretrained during 215 epochs in pascal VOC dataset.

For instance I was using this command :

Python train.py —num-class 26 —class-names ./dataset/names/list_class.names —network inceptionv3 —pretrained ./model/inceptionv3 —end-epoch 300 —data-shape 512 —finetune 1

And in my model’s folder I had: 
Inceptionv3-0001.params
Inceptionv3_512-symbol.json

So I think if you take the same command replace inceptionv3 by mobilenet and rename the two file at : 
Mobilenet-0001.params and 
Mobilenet_512-symbol.json
It will work

**Comment by Rizhiy** [comment]
Thanks, that sort of worked, at least now it doesn't crash.
I get `nan` for CrossEntropy and SmoothL1 straight away for some reason, do you have any idea why that might be?

**Comment by ACkuku** [comment]
@Ferbach I trained my own dataset, but the Validation-mAP=0, I have no idea about this, and do you konw why? thanks

**Comment by Ferbach** [comment]
No I don’t know why, maybe with more details I can tell you

**Comment by ACkuku** [comment]
@Ferbach thanks for your reply.
here is my train command:
`python train.py --train-path train.rec --train-list train.lst --val-path val.rec --val-list val.lst --network inceptionv3 --finetune 215 --prefix ./model/ssd_inceptinv3_512 --batch-size 32 --lr 0.001 -data-shape 512 -gpus 0,1 --num-example 21197 --num-class 1 --class-names rear`
and when it fineshed one epoch, the validation-rear=0, the validation-map=0. 
Begin training, I check the .rec file, and draw the box on image, it's correct.

**Comment by Ferbach** [comment]
It doesnt seem like you have made a mistake, I have trained with 20,24 and 82 classes without any problem but I’m currently trainning a model with only 1 class and I have the same issue, if I find something I will tell you
