### ISSUE TITLE
train_object_acc goes down during training

### ISSUE THREAD

**Issue by xinghedyc** [zhreshold/mxnet-ssd#15]
Hi,
I use this code to train on pascal dataset and I find that the train_objectacc goes down during training.
logs are like these:
Start training with (gpu(0)) from pretrained model /home/dyc/workspace/mxnet-ssd/model/vgg16_reduced
Freezed parameters: INFO:root:Epoch[1] Batch [20]	Speed: 33.88 samples/sec	Train-Acc=0.748112
INFO:root:Epoch[1] Batch [20]	Speed: 33.88 samples/sec	Train-ObjectAcc=0.009007
INFO:root:Epoch[1] Batch [20]	Speed: 33.88 samples/sec	Train-SmoothL1=98.478310
INFO:root:Epoch[1] Batch [40]	Speed: 33.42 samples/sec	Train-Acc=0.747074
INFO:root:Epoch[1] Batch [40]	Speed: 33.42 samples/sec	Train-ObjectAcc=0.007426
INFO:root:Epoch[1] Batch [40]	Speed: 33.42 samples/sec	Train-SmoothL1=93.499833
INFO:root:Epoch[1] Batch [60]	Speed: 33.74 samples/sec	Train-Acc=0.749589
INFO:root:Epoch[1] Batch [60]	Speed: 33.74 samples/sec	Train-ObjectAcc=0.003738
INFO:root:Epoch[1] Batch [60]	Speed: 33.74 samples/sec	Train-SmoothL1=95.395453
INFO:root:Epoch[1] Batch [80]	Speed: 33.89 samples/sec	Train-Acc=0.749490
INFO:root:Epoch[1] Batch [80]	Speed: 33.89 samples/sec	Train-ObjectAcc=0.003148
INFO:root:Epoch[1] Batch [80]	Speed: 33.89 samples/sec	Train-SmoothL1=87.185657
INFO:root:Epoch[1] Batch [100]	Speed: 34.06 samples/sec	Train-Acc=0.749362
INFO:root:Epoch[1] Batch [100]	Speed: 34.06 samples/sec	Train-ObjectAcc=0.001884
INFO:root:Epoch[1] Batch [100]	Speed: 34.06 samples/sec	Train-SmoothL1=101.286346
INFO:root:Epoch[1] Batch [120]	Speed: 33.98 samples/sec	Train-Acc=0.750000
INFO:root:Epoch[1] Batch [120]	Speed: 33.98 samples/sec	Train-ObjectAcc=0.000000
INFO:root:Epoch[1] Batch [120]	Speed: 33.98 samples/sec	Train-SmoothL1=95.370920

**Comment by zhreshold** [comment]
This is normal, just be patient, it will goes up again.

**Comment by xinghedyc** [comment]
@zhreshold Thanks a lot!
