### ISSUE TITLE
mscoco python 3 compatability

### ISSUE THREAD

**Issue by Rizhiy** [zhreshold/mxnet-ssd#150]
In [mscoco.py](https://github.com/zhreshold/mxnet-ssd/blob/955b3c1228f372fda430f6e0bb1f32ebff266e5c/dataset/mscoco.py#L110) you try to do the following:
```python
            indices = range(len(image_set_index))
            random.shuffle(indices)
```
`range()` is an iterator in python 3, therefore can't be shuffled. To fix this use `list()`:
```python
            indices = list(range(len(image_set_index)))
            random.shuffle(indices)
```

**Comment by Rizhiy** [comment]
Decided to make a pull request, although its small issue. #151

**Comment by zhreshold** [comment]
Merged
