### ISSUE TITLE
Training mobilenet

### ISSUE THREAD

**Issue by Rizhiy** [zhreshold/mxnet-ssd#153]
How do I train mobilenet? When I try to run `train.py --network mobilenet` it says `Failed to open ... vgg16_reduced-symbol.json`.

Why do I need `vgg16_reduced` to train mobilenet / where do I get `mobilenet_reduced`?

**Comment by davsol** [comment]
The default path for the model is for the vgg one,
You need to specify the pretrained model path, or alternatively train from
scratch

2017-12-05 18:02 GMT+02:00 Artem Vasenin <notifications@github.com>:

**Comment by Rizhiy** [comment]
How do I train from scratch?

**Comment by davsol** [comment]
Add the flag
--pretrained ' '

**Comment by Rizhiy** [comment]
Thanks
