### ISSUE TITLE
Multi-scale training and prediction

### ISSUE THREAD

**Issue by arcadiaphy** [zhreshold/mxnet-ssd#156]
I have used ssd to detect texts in which the training input is 300x300, but the prediction input needs to be in different scales. But in practice, when I have changed the input scale, the prediction results is not right at all. After inspecting the caffe ssd implementation, I have found the reason:
```
min_dim = 300
...
min_ratio = 20
max_ratio = 90
step = int(math.floor((max_ratio - min_ratio) / (len(mbox_source_layers) - 2)))
min_sizes = []
max_sizes = []
for ratio in xrange(min_ratio, max_ratio + 1, step):
  min_sizes.append(min_dim * ratio / 100.)
  max_sizes.append(min_dim * (ratio + step) / 100.)
min_sizes = [min_dim * 10 / 100.] + min_sizes
max_sizes = [min_dim * 20 / 100.] + max_sizes
```
In caffe, the sizes of the anchor boxes are measured in pixels, while in mxnet, they are measured in proportion by scaling to 0-1 of input size. This is very important in multi-scale prediction because the receptive field of one convolution kernel does not change regardless of input size. So the model will hold in another input size only if the anchor box size is fixed, not depending on input size.

After changing the anchor box sizes to pixels, the MultiboxPrior layer should be modified according to caffe implementation:
```
        net[name] = L.PriorBox(net[from_layer], net[data_layer], min_size=min_size,
                clip=clip, variance=prior_variance, offset=offset)
```
The input data symbol should be included in arguments to cast pixel anchor size back to 0-1.

After making these changes, [Textboxes](https://github.com/MhLiao/TextBoxes) can be reproduced with good performance.

Maybe the official mxnet example can also be revised likewise.

**Comment by zhreshold** [comment]
This issue has been recognized long time ago. What you have mentioned is a correct way to solve it, but will break the backward compatibility. I am still seeking a way to retain the current model compatibility.

**Comment by arcadiaphy** [comment]
Backward compatibility is really a headache. Maybe at least add a notice in REAME, it takes me a lot of time to find the reason.

**Comment by goodtogood** [comment]
@arcadiaphy 
I  met the same problem ,  would you like to share the code you modified?
thx.

**Comment by arcadiaphy** [comment]
@goodtogood 
I have port my modification to the latest ssd code, please refer to my forked [repo](https://github.com/arcadiaphy/mxnet-ssd).

The backward compatibility is totally broken. Here is an example to setup MultiBoxPrior:
```
    sizes = [[30., 42.4], [60., 82.7], [114., 138.4], [168., 193.1], [222., 247.5], [276., 301.8]]
    ratios = [[1, 2, 3, 5, 7, 10], [1, 2, 3, 5, 7, 10], [1, 2, 3, 5, 7, 10], [1, 2, 3, 5, 7, 10], [1, 2, 3, 5, 7, 10], [1, 2, 3, 5, 7, 10]]
    anchors = mx.contrib.symbol.MultiBoxPrior(
        *[from_layer, data], sizes=sizes[0], ratios=ratios[0],
        clip=True, name=name, steps=[], textboxes=True)
```

Changes to MultiBoxPrior layer:
- add image input variable data to argument
- `sizes` should be measured in pixels, not normalized to 0-1
- `steps` should be set to [] in multi-scale prediction to enable automatic calculation

**Comment by goodtogood** [comment]
@arcadiaphy   thanks a lot !

**Comment by kalyc** [comment]
Hi @zhreshold would you recommend leaving the current implementation as is for backward compatibility in that case?
