### ISSUE TITLE
pretrain from resnet50 might be broken

### ISSUE THREAD

**Issue by goodtogood** [zhreshold/mxnet-ssd#158]
Hi,
 error occurred when pretrain, I downloaded [resnet-50-0000.param](http://data.dmlc.ml/mxnet/models/imagenet/resnet/50-layers/)s && resnet-50-symbol.json and putting them in folder model. 

> Traceback (most recent call last):
>   File "train.py", line 148, in <module>
>     tensorboard=args.tensorboard)
>   File "E:\MxNetAll\ssd\train\train_net.py", line 286, i
> n train_net
>     output_dir=os.path.dirname(prefix), train=False, num_classes=num_classes)
>   File "E:\MxNetAll\ssd\tools\visualize_net.py", line 35
> , in net_visualization
>     net = symbol_factory.get_symbol(network, data_shape, num_classes=num_classes
> )
>   File "E:\MxNetAll\ssd\tools\..\symbol\symbol_factory.p
> y", line 217, in get_symbol
>     return symbol_builder.get_symbol(**config)
>   File "E:\MxNetAll\ssd\symbol\symbol_builder.py", line
> 157, in get_symbol
>     min_filter=min_filter)
>   File "E:\MxNetAll\ssd\symbol\common.py", line 124, in
> multi_layer_feature
>     layer = internals[from_layer.strip() + '_output']
>   File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\symbol\symbo
> l.py", line 508, in __getitem__
>     raise ValueError('Cannot find output that matches name \"%s\"' % index)
> ValueError: Cannot find output that matches name "_plus12_output"

when trying resnet101, similar problem

> ValueError: Cannot find output that matches name "_plus29_output"

**Comment by yafz** [comment]
Did you solve this problem?

**Comment by hardfish82** [comment]
You can comment "net_visualization" and try again. This error will be disappeared. But I found more errors. I compared differences between resnet and vgg pretrained model(which works fine). resnet has some layers which relate to output classes number. So is this a problem of the resnet pretrained model?

**Comment by hardfish82** [comment]
I finally resolved this problem myself. Because I changed the output classed number, so the finetune should be set to the pretrained model epoch number.

**Comment by renatodmb** [comment]
Could you solve this problem?
I have the same:
- resnet101
raise ValueError('Cannot find output that matches name \"%s\"' % index)
ValueError: Cannot find output that matches name "_plus29_output"
- resnet50
raise ValueError('Cannot find output that matches name \"%s\"' % index)
ValueError: Cannot find output that matches name "_plus12_output"

* Vgg works fine

**Comment by zhreshold** [comment]
@renatodmb You should use http://data.dmlc.ml/models/imagenet/resnet/50-layers/ as the pre-trained models
