### ISSUE TITLE
How to evaluate on a single image

### ISSUE THREAD

**Issue by huliang2016** [zhreshold/mxnet-ssd#159]
I've trained a new model on my own dataset. I was wondering how to evaluate on a single image? thanks!

**Comment by huliang2016** [comment]
I've done this, thanks!

**Comment by aa12356jm** [comment]
@huliang2016  Are you using gpu？i can't get the gpu to work ,can you give me some ideas? thanks

**Comment by huliang2016** [comment]
yep, have you install mxnet? of course you have to install cudnn and cuda first.

**Comment by yahyanik** [comment]
hey guys,
I am very new to this. I have finished training too, but still unable to run my model for an image. Can you please tell me how you achieved this? also I am not using GPU if this makes thing easier.

Thanks a lot.

**Comment by zhreshold** [comment]
Please checkout the usage of demo.py using `--help`

**Comment by yahyanik** [comment]
my problem is that even the demo is not working. it says there is no 'resnet' in import module in symbol.builder.

**Comment by zhreshold** [comment]
@yahyanik I though python3 was fixed, but apparently not. You can use python2 in the meantime I fixing it.

**Comment by yahyanik** [comment]
I figured it out. Python 2.7 works. Thank you again for the response and code. Happy New Year
