### ISSUE TITLE
How to convert ssd model to Apple CoreML format

### ISSUE THREAD

**Issue by libennext** [zhreshold/mxnet-ssd#171]
Hi, I would like to convert the ssd model ( xxx.params and xxx.json) to coreml format, but I can not find a tutorial (ssd model) in readme file of [mxnet-coreml-tools](https://github.com/apache/incubator-mxnet/tree/master/tools/coreml), could you give me a suggestion how to do this, and how to construct the synset.txt file for ssd model? Thanks! @zhreshold @Prasad9

**Comment by zhreshold** [comment]
Some operators are not supported by coreml, so you can't directly export to apple device currently.

**Comment by libennext** [comment]
@zhreshold Thanks!
