### ISSUE TITLE
MobileNet 224?

### ISSUE THREAD

**Issue by kuonangzhe** [zhreshold/mxnet-ssd#176]
@zhreshold Hi, I notice that at symbel factory's comment, for mobilenet it shows 224 as the input size, but the model given in README is 512 and 608. So is there a mobilenet 224, or why is there a 512 sized model? I am a bit confused about this part. 

Thanks a lot!

**Comment by zhreshold** [comment]
Reason is simple, 224 is for image classification, which is too small for object detection.
