### ISSUE TITLE
Some notices for the the newest version. 

### ISSUE THREAD

**Issue by PeterChenYijie** [zhreshold/mxnet-ssd#178]
VERSION: 
 * `python 3.6.2+`
 * `mxnet-GPU 1.0.0+` or `mxnet 1.0.0+` 

issues fixed:
* if you get the `ModuleNotFoundError: No module named 'common' `,it must be you should the newer mxnet version.It has got change in common[here]( https://github.com/apache/incubator-mxnet/blob/b2ce81218b13c3140dc3d2fd9fa27a1dd0264b75/example/ssd/symbol/symbol_builder.py ).Please change to `from symbol.common import multi_layer_feature, multibox_layer` in [symbol_builder.py](https://github.com/zhreshold/mxnet-ssd/blob/master/symbol/symbol_builder.py)
*  Perhaps change `xrange` to `range` in python3.6+ version  

Many Thanks!

**Comment by apivovarov** [comment]
zhreshold/mxnet-ssd works only with python2
