### ISSUE TITLE
Train error with Pretrained resnet50_512 

### ISSUE THREAD

**Issue by qilicun** [zhreshold/mxnet-ssd#188]
Hi!
Firstly, thanks very much for your work, that helps me a lot!
Secondly, when I run training with pretrained resnet50_512 an error happends, but if training from scratch with resnet50_512 , everything goes fine.  Please point me where I got wrong. Thanks!

**Part of the command for training**
```
 python train.py --gpus 0 --network resnet50 --data-shape 512 --pretrained model/ssd_resnet50_512 --epoch 0 
```
**Error msg**
```
mxnet.base.MXNetError: [15:35:15] src/operator/nn/./../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [84], got [8]

```

**Comment by qilicun** [comment]
But when I download the v0.2 VGG16_reduced, everything works fine. So I'm wondering if the there is some mismatch between resnet50 weights and symbol?

**Comment by qilicun** [comment]
I notice there is a seam issue here. https://github.com/zhreshold/mxnet-ssd/issues/124
Since own dataset has only one class, the pretrained model on VOC has 20 classes, this leads to the mismatch. But I don't know why I can your pretrained VOC  model to train my own dataset with mxnet-yolo? Thanks!

**Comment by qilicun** [comment]
After training with 19 dummy class, the pretrained model works fine... 
Will close this issue, but still wondering how to use this pretrained model with classes not equal to 20.

**Comment by hardik2396** [comment]
Have you found the answer  ?
