### ISSUE TITLE
I run demo.py , a error raise

### ISSUE THREAD

**Issue by poorfriend** [zhreshold/mxnet-ssd#19]
Traceback (most recent call last):
  File "E:/opensource/mxnet-master/example/ssd/demo.py", line 95, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "E:/opensource/mxnet-master/example/ssd/demo.py", line 39, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "E:\opensource\mxnet-master\example\ssd\symbol\symbol_vgg16_reduced.py", line 163, in get_symbol
    net = get_symbol_train(num_classes)
  File "E:\opensource\mxnet-master\example\ssd\symbol\symbol_vgg16_reduced.py", line 54, in get_symbol_train
    pooling_convention="full", name="pool3")
  File "E:\opensource\mxnet\python\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
  File "E:\opensource\mxnet\python\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Cannot find argument 'pooling_convention', Possible Arguments:

**Comment by zhreshold** [comment]
You must be using the downloaded version of the official repo, use the submodule I provided.
For windows, the have to build the lib with the submoudle as well.

**Comment by zhreshold** [comment]
All your errors are related to this, I'm gonna close the other two issues.

**Comment by Lvhhhh** [comment]
your code is included in examples of mxnet. how to use it? 
i have install the mxnet.  and i found the ssd code in examples of it .how can i do in win10?

**Comment by zhreshold** [comment]
If you are using the official repo, read the README first in that repo.
For windows, follow the instructions of how to install on windows

**Comment by Lvhhhh** [comment]
sorry. i have install mxnet from the official repo. and have read the README from that repo. but...Is "the lib with the submoudle " you said the same as the  lib folk include libmxnet.dll and libmxnet.lib  created by the prebuild package??

**Comment by Lvhhhh** [comment]
my computer cannot install the OpenBlas. so i use the prebuilt MXNet package. does it have effect??

**Comment by Lvhhhh** [comment]
but i still have this problem when i run python demo.py in your folk.

**Comment by zhreshold** [comment]
Pre-build windows lib don't have ssd custom layers enabled. You have to build the lib using my fork of mxnet.

**Comment by Lvhhhh** [comment]
'thanks!! but when i compile the mxnet.sln to generate the "libmxnet.dll". it comes "error MSB6006 cmd.exe exited with code 1".i know it is not your code problem. but i dont know how to solve it. so i ask for your help. thks!!

**Comment by Lvhhhh** [comment]
error MSB6006 cmd.exe exited with code 1	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	mxnet

**Comment by Lvhhhh** [comment]
win10+cudnnv3+vs2013.

**Comment by zhreshold** [comment]
If you still can't resolve the problem, try use the one I prebuilted: https://github.com/zhreshold/mxnet-ssd.cpp/tree/win/lib, it's built with vs2015/vc14, no guarantee to work with vs2013

**Comment by Lvhhhh** [comment]
thanks, i got the reason, because of cuda7.5 and win10!!i change the cuda 7.5 to 8.0. it is solved,

**Comment by edmBernard** [comment]
By chance have you a version of the compiled files libmxnet.dll and libmxnet.lib with ssd and with gpu support.
That would help me a lot.

**Comment by zhreshold** [comment]
@edmBernard Follow the official guide of how to build using visual studio, basically same procedure. I only have libmxnet.dll without gpu: https://github.com/zhreshold/mxnet-ssd.cpp/tree/win

**Comment by edmBernard** [comment]
@zhreshold I want to avoid compilation process and configuration on windows
I think that can be avoided

**Comment by zhreshold** [comment]
Now mxnet has prebuilt pip packages that is good enough to work. Closing this.
