### ISSUE TITLE
Gradient is not rescaled for adadelta optimizer

### ISSUE THREAD

**Issue by indhub** [zhreshold/mxnet-ssd#191]
I see that gradients are not rescaled for adadelta optimizer. Even for the other optimizers, gradient is not divided by batch_size. Is this a bug?

When using adadelta optimizer in distributed training, using different number of devices/hosts gives very different loss even when the effective batch size is the same. Rescaling gradients as shown below seems to fix the problem.

```
     elif optimizer.lower() == 'adadelta':
         opt = 'adadelta'
-        optimizer_params = {}
+        rescale_grad = 1.0 / batch_size / nworker
+        optimizer_params = {'rescale_grad': rescale_grad}

```
Note: nworker is the number of workers in distributed training. batch_size is per-host batch size.

Even when distributed training is not used, I think the gradient should be divided by the batch_size since the gradient obtained after backward pass is sum of gradient from all examples in the batch.

**Comment by zhreshold** [comment]
rescale grad for SGD is overwritten deliberately to cooperate with `sym.MakeLoss` with `normalization` mode.  It does not fit `adadelta`, but you can modify it a bit to make sure gradients are correctly rescaled.

**Comment by indhub** [comment]
Do you know why adadelta doesn't require rescaling but Adam does? I'm trying to understand what's different.
