### ISSUE TITLE
Images without object as background in SSD

### ISSUE THREAD

**Issue by lixiangchun** [zhreshold/mxnet-ssd#192]
Is it possible to include images without object as negative samples (like YOLO) via running SSD?

BTW, is there some scripts to prepare input files to run `mxnet-ssd` from YOLO annotation result?

**Comment by ddlee96** [comment]
There is a `ture_negative' parameter in dataset class, whose default value is `False`. In that case, images without GT will be filtered. You can change it when prepare dataset. Hope it's helpful.

**Comment by lixiangchun** [comment]
@ddlee96 Thanks for your reply. One more question, when finished running data preparation script file, I obtained a list file with the following content:

```
0       2       5       1.0000  0.5278  0.2917  0.6528  0.4392    positive/1.jpg
2       2       5       0.0000  0.5878  0.3895  0.6496  0.4794    negative/2.jpg
``` 
For a `true_negative` images, what is the values of columns 5 to 8? 

I failed to figure out what they would be from the following function:
```python
    def _filter_image_with_no_gt(self):
        """
        filter images that have no ground-truth labels.
        use case: when you wish to work only on a subset of pascal classes, you have 2 options:
            1. use only the sub-dataset that contains the subset of classes
            2. use all images, and images with no ground-truth will count as true-negative images
        :return:
        self object with filtered information
        """

        # filter images that do not have any of the specified classes
        self.labels = [f[np.logical_and(f[:, 0] >= 0, f[:, 0] <= self.num_classes-1), :] for f in self.labels]
        # find indices of images with ground-truth labels
        gt_indices = [idx for idx, f in enumerate(self.labels) if not f.size == 0]

        self.labels = [self.labels[idx] for idx in gt_indices]
        self.image_set_index = [self.image_set_index[idx] for idx in gt_indices]
        old_num_images = self.num_images
        self.num_images = len(self.labels)

        print ('filtering images with no gt-labels. can abort filtering using *true_negative* flag')
        print ('... remaining {0}/{1} images.  '.format(self.num_images, old_num_images))

```

**Comment by ddlee96** [comment]
Yeah, this function is called when you flilter images without GT out. In `save_imglist` method of `Imdb` class, the labels witsh size<1 are simply skipped when creating `*.lst` files.

**Comment by lixiangchun** [comment]
@ddlee96 For true negative samples, if they were not excluded, what would be the values of columns 5 to 8 as I posted before:

```
0       2       5       1.0000  0.5278  0.2917  0.6528  0.4392    positive/1.jpg
2       2       5       0.0000 0.5878  0.3895  0.6496  0.4794    negative/2.jpg
```

The above two showed examples of two images with objects.

For those without object (i.e. true negative), what would be the values of columns 5 to 8? Are they all zeros? or just left as blank?

**Comment by zhreshold** [comment]
should be -1s

**Comment by lixiangchun** [comment]
@zhreshold Thank you. The 4th column is class id. For the true negative sample, should we assign a unique class id to true negative sample or we also need to set it to -1?

**Comment by ddlee96** [comment]
@lixiangchun There is an `label_pad_value` parameter in class `ImageDetRecordIter`, so that images with non-maxiumum gt boxes will be paded with dummy boxes with -1 as its class_id(then all images will have the same shape in a single batch). The -1 label boxes will be ignored in assgning anchor process which implemented in `MultiboxTarget` Operator. In your case, I suppose generate a dummy box whose class_id and coordinates are -1 will do ther trick.

**Comment by lixiangchun** [comment]
@ddlee96 Thanks for your comment.
