### ISSUE TITLE
How to get the feature map of any layer?

### ISSUE THREAD

**Issue by nvnnghia** [zhreshold/mxnet-ssd#193]
I want to get output of one layer in the network, can anyone tell me how can I do that? Thank you

**Comment by ddlee96** [comment]
You can try 
```
internals = body.get_internals()
layer_output = internals[$layer_name + '_output']
```

Or cut the symbol in a specific layer and save it as another symbol, use `save_checkpoint()` to save params and states of this cutted network. Then you can get outputs as normal. Hope it's helpful.

**Comment by nvnnghia** [comment]
Thank you!
