### ISSUE TITLE
PR to MXNet/examples?

### ISSUE THREAD

**Issue by piiswrong** [zhreshold/mxnet-ssd#2]
This looks cool. Would you like to PR it to mxnet main repo so we can make sure upstream updates don't break it?
Also if you can put numbers in readme it would be great.

**Comment by zhreshold** [comment]
Yep, was thinking about it. When I finished re-organizing the structure to an example, I will submit a PR.

**Comment by piiswrong** [comment]
Please put the ssd specific layers into plugin if you think no other model will possibly reuse them

**Comment by tornadomeet** [comment]
great example
