### ISSUE TITLE
evaluate metric is lower than train？

### ISSUE THREAD

**Issue by shuikehuo** [zhreshold/mxnet-ssd#204]
On training ，mAP = 75，but On evaluating， mAP =72.6. why？（train：voc07 trainval test：voc07 test）

**Comment by nvnnghia** [comment]
which metric you used? VOC2007 metric?

**Comment by shuikehuo** [comment]
yes，I used  voc2007 metric

**Comment by nvnnghia** [comment]
just set it to False.

**Comment by shuikehuo** [comment]
It works fine. thanks a lot
