### ISSUE TITLE
使用默认参数训练VOC数据NAN

### ISSUE THREAD

**Issue by Jack-CV** [zhreshold/mxnet-ssd#207]
@zhreshold 你好，感谢你的代码。我使用默认参数（python train.py --gpus 0,1 --batch-size 32 ）训练VOC数据，训练若干个epoch后loss总是会NAN，你训练时候有这种现象么

![image](https://user-images.githubusercontent.com/38135837/39963412-11e39e3e-569d-11e8-90e2-eb0910f077b4.png)

**Comment by Jack-CV** [comment]
@zhreshold 我总是会遇到这个问题，但每次出现问题的epoch都不太一样

**Comment by zhreshold** [comment]
Possibly your data is corrupted, or GPU is not in good condition which may randomly cause flipped bit in GPU memory

**Comment by hdjsjyl** [comment]
这就是我放弃用rec文件的code的原因, 每次用rec文件的才会出现这个问题, 其他的都没问题.

**Comment by enjoyyi00** [comment]
i also meet this problem, how do you solve this?

**Comment by zhreshold** [comment]
Update mxnet to latest version, there used to be a bug but it's fixed after 1.4.1
