### ISSUE TITLE
when I run make using gpu, there is an error that VarInfo is ambiguous.

### ISSUE THREAD

**Issue by chenwgen** [zhreshold/mxnet-ssd#21]
example/ssd/operator/./multibox_detection-inl.h:115:136: error: call of overloaded 'VarInfo(<brace-enclosed initializer list>)' is ambiguous
     DMLC_DECLARE_FIELD(variances).set_default(VarInfo({0.1f, 0.1f, 0.2f, 0.2f}))
                                                                                                                                        ^
example/ssd/operator/./multibox_detection-inl.h:115:136: note: candidates are:
example/ssd/operator/./multibox_detection-inl.h:30:10: note: mxnet::op::VarInfo::VarInfo(std::vector<float>)
   explicit VarInfo(std::vector<float> in) : info(in) {}
          ^
example/ssd/operator/./multibox_detection-inl.h:28:8: note: mxnet::op::VarInfo::VarInfo(const mxnet::op::VarInfo&)
 struct VarInfo {
        ^
example/ssd/operator/./multibox_detection-inl.h:28:8: note: mxnet::op::VarInfo::VarInfo(mxnet::op::VarInfo&&)
make: *** [example/ssd/operator/multibox_detection_gpu.o] Error 1

**Comment by zhreshold** [comment]
cuda version?

**Comment by chenwgen** [comment]
cuda-7.0

**Comment by zhreshold** [comment]
Compiler don't support vector initialization list. 
If you feel comfortable, update cuda to the latest version, i.e. 8.0

**Comment by chenwgen** [comment]
But when I don't use cuda, the same error also happens, is it related to compiler?

**Comment by zhreshold** [comment]
I guess your gcc is too old.

**Comment by chenwgen** [comment]
So which version of gcc can be ok?  thanks.

**Comment by zhreshold** [comment]
4.8.6+ should be good enough. 4.9+ could be better. I don't have any test machine to verify that.
