### ISSUE TITLE
Error: daviddocker78:mxnet-ssd:gpu_0.12.0_cuda9 is not a valid repository/tag

### ISSUE THREAD

**Issue by LuckyPigeon** [zhreshold/mxnet-ssd#212]
@zhreshold Hey there, I found this error when I was implement your tutorial, it should be like daviddocker78/mxnet-ssd:gpu_0.12.0_cuda9 could you correct the doc? Thanks!

**Comment by zhreshold** [comment]
Fixed, thanks for spotting the error!
