### ISSUE TITLE
Get error during "Train the model" stage

### ISSUE THREAD

**Issue by WIll-Xu35** [zhreshold/mxnet-ssd#213]
Hi there, I'm trying to implement mxnet-ssd by following your instructions. But I got error while executing "bash tools/prepare_pascal.sh". The error message is in the the attachment.

Could you please help me find out what is wrong with my approach?

Thanks!

![im2rec](https://user-images.githubusercontent.com/40563560/41883376-ebd12ac6-7920-11e8-9b93-e6c7df79a269.png)

**Comment by zhreshold** [comment]
`--shuffle` and `--pack-label` no longer take 1 as argument in latest mxnet.
So you can simply remove them in prepare_pascal.sh

**Comment by WIll-Xu35** [comment]
OMG, thanks!

**Comment by WIll-Xu35** [comment]
This line that gets me error message seems to be in prepare_dataset.py. Do I have to delete the entire line or I have to change some parameters to meet the requirements of the latest mxnet? And once the training set is not shuffled, will there be a problem getting a good performance?

Thanks!

**Comment by zhreshold** [comment]
previous usage is `--shuffle 1` or `--shuffle 0`, but now it defaults to use shuffle, and user can use `--no-shuffle` for validation dataset.

"And once the training set is not shuffled, will there be a problem getting a good performance?" - Yes

**Comment by WIll-Xu35** [comment]
I deleted those parameters in prepare_dataset.py and it seems to work fine.
Many thanks!
