### ISSUE TITLE
mxnet-ssd with NNPACK?

### ISSUE THREAD

**Issue by PhanTask** [zhreshold/mxnet-ssd#22]
I want to speed up mxnet-ssd with NNPACK, but after I download the latest version of mxnet which supports NNPACK I found out that I cannot use it by simply replace the mxnet in your project(mx.symbol.Scale not found, which is already pointed out by Jiakui).
So are there any solutions about how to use the latest version of mxnet instead of the mxnet in your project or how to use NNPACK in the mxnet in your project?Any suggestions would be greatly appreciated.

**Comment by zhreshold** [comment]
Check out the that this example is available in official repo under example/ssd

**Comment by PhanTask** [comment]
@zhreshold 
Thank you, I tried example/ssd, but unfortunately I got another error:
example/ssd/symbol/common.py line 164 in multibox_layer
anthor = mx.symbol.MultiBoxPrior(from_layer……
AttributeError: 'module' object has no attribute 'MultiBoxPrior'
Before that I just gitted the latest version of mxnet and maked it with setting 'NNPACK' & 'openblas' enabled.
Then I entered mxnet/python and run 'python setup.py install'
It seems that my mxnet still have some problems.
BTW, I can't uninstall mxnet thoroughly by pip. After I do pip uninstall mxnet, the mxnet(0.7.0) still exists in pip list. So I think maybe this is the reason why I can't find MultiBoxPrior.
Do you know how to solve this?

**Comment by PhanTask** [comment]
@zhreshold 
I tried example/ssd and it works, thank you!
