### ISSUE TITLE
ModuleNotFoundError: No module named 'common'

### ISSUE THREAD

**Issue by hsqaihkl** [zhreshold/mxnet-ssd#229]
@zhreshold Hi，
   I download your code to run in pycharm I run the project but i have  met a problem ：**

<module 'mxnet' from '/home/water/.local/lib/python3.7/site-packages/mxnet/__init__.py'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
Traceback (most recent call last):
  File "/home/water/PycharmProjects/mxnet-ssd/demo.py", line 7, in <module>
    from symbol.symbol_factory import get_symbol
  File "/home/water/PycharmProjects/mxnet-ssd/symbol/symbol_factory.py", line 3, in <module>
    from symbol import symbol_builder
  File "/home/water/PycharmProjects/mxnet-ssd/symbol/symbol_builder.py", line 2, in <module>
    from common import multi_layer_feature, multibox_layer
ModuleNotFoundError: No module named 'common'

**Comment by wisdomk** [comment]
hey,
check #178

**Comment by apivovarov** [comment]
use python2

**Comment by apivovarov** [comment]
You can try `export PYTHONPATH=.../mxnet-ssd/symbol` but you will face other python3 issues...
https://github.com/zhreshold/mxnet-ssd/issues/232

**Comment by hsqaihkl** [comment]
> You can try `export PYTHONPATH=.../mxnet-ssd/symbol` but you will face other python3 issues...
> #232

Ok,thanks,
Is that any other SSD which run in mxnet and python3?

**Comment by zhreshold** [comment]
try ssd example in https://github.com/apache/incubator-mxnet/tree/master/example/ssd, fixed with python3
