### ISSUE TITLE
sizes of  PriorBox  wonder

### ISSUE THREAD

**Issue by nopattern** [zhreshold/mxnet-ssd#25]
I find the sizes of PriorBox in your code 
        sizes = [[.1], [.2,.276], [.38, .461], [.56, .644], [.74, .825], [.92, 1.01]].
       The  original is 
           min_sizes = []
           max_sizes = []
          for ratio in xrange(min_ratio, max_ratio + 1, step):
                 min_sizes.append( ratio / 100.)
                 max_sizes.append((ratio + step) / 100.)
          min_sizes = [ 10 / 100.] + min_sizes
          max_sizes = [[]] + max_sizes 

     which can be translated as  [[0.1],[0.2,0.38],[0.38,0.56],[0.56,0.74],[0.74,0.92],[0.92,1.1]].

  why do you left some space between ranges such as [.2,.276], [.38, .461]?

**Comment by zhreshold** [comment]
You will find max_size = sqrt(min_size * max_size) in caffe layer. I just found it's better not hiding the implementation details.

**Comment by nopattern** [comment]
Thank you .  I find  the code in Prior_box_layer.cpp .        
             box_width = box_height = sqrt(min_size_ * max_size_);

**Comment by chi0tzp** [comment]
Can you explain what `min_sizes` and `max_sizes` mean? I know that they correspond to the minimum and maximum objects, respectively, in the various scales, but how have the exact values been computed? Because they don't seem exactly "heuristic".
Thanks!
