### ISSUE TITLE
very slow inference

### ISSUE THREAD

**Issue by amlarraz** [zhreshold/mxnet-ssd#26]
Hi! when i run a inference using demo.py these take a lot of time (minimum 30 secs. I not speak about the detection time but the starting-net time), is it normal? there is some way to run faster the inferences? in others net or frameworks like Yolo in darknet, you can "activate" the net (load weights and more) and after you can load some images separately...something like this in mxnet?
Thanks in advance!

**Comment by zhreshold** [comment]
First of all. 30 secs seems to be the time required to initialize the library. Normally after first run, it only took several ms to initialize again including loading model. 
Second, per you question, it is doable to load the model and hold for inputs. If you dig into the code, you will find detection happens in detect/detector.py, where network is loaded by module, and module will predict using images after that. If you don't release the module and wait for more inputs, then the overhead will be minimal.
