### ISSUE TITLE
Any chances to train SSD512?

### ISSUE THREAD

**Issue by SpecialM2580** [zhreshold/mxnet-ssd#27]
Plz show me the way , i'm still a new bee...Any chance to upload the SSD512 model?

**Comment by zhreshold** [comment]
Well it needs some modification to network structure, I have no plan to write it in a near future. If you are interested, follow the example in symbol/symbol_vgg16_reduced.py and the original ssd 512.
Basically some parameters have to be changed.

**Comment by SpecialM2580** [comment]
Thanks~

**Comment by larrycheungbai** [comment]
Hi All,
I also want to train a larger SSD model.
Can we discuss?
Best regards.
