### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Scale'

### ISSUE THREAD

**Issue by lps683** [zhreshold/mxnet-ssd#3]
Hello,i'm really interested in your project,but i have some problems when i run your project as follow:

Traceback (most recent call last):
  File "demo.py", line 93, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 39, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/home/jackqian/mxnet-ssd-master/symbol/symbol_vgg16_reduced.py", line 162, in get_symbol
    net = get_symbol_train(num_classes)
  File "/home/jackqian/mxnet-ssd-master/symbol/symbol_vgg16_reduced.py", line 118, in get_symbol_train
    clip=True, interm_layer=0)
  File "/home/jackqian/mxnet-ssd-master/symbol/common.py", line 111, in multibox_layer
    from_layer = mx.symbol.Scale(data=from_layer, mode="spatial", \
AttributeError: 'module' object has no attribute 'Scale'

it seems that we cannot find the module 'Scale'.
I really want to run this project in MXNet so i pluck up courage to ask you for help.i'll appreciate it if you can help me!
By the way,i‘m a new learner!
Thanks!

**Comment by zhreshold** [comment]
You might be using the official branch of mxnet. Use git clone --recurisve to pull the entire repository, and follow the instruction again.

**Comment by Walid-Ahmed** [comment]
I installed MXNET  using instructions from http://mxnet.io/get_started/osx_setup.html
**then**
I used git clone --recursive https://github.com/zhreshold/mxnet-ssd.git

I still have the same error
AttributeError: 'module' object has no attribute 'Scale' 

Do I have to build MXNET ~/mxnet-ssd/mxnet?
