### ISSUE TITLE
Wrong number of priors computations ?

### ISSUE THREAD

**Issue by wonwoolee** [zhreshold/mxnet-ssd#34]
Hi,
Looks like there is a small bug in computing the number of anchors in _mxnet-ssd/symbol/common.py_ at line **129**: ` num_anchors = len(size) -1 + len(ratio)`

Shouldn't it be something like: 
` num_anchors = (len(size) -1) * len(ratio)`   ???

**Comment by zhreshold** [comment]
It was designed to be like this, to avoid generating too much priors
