### ISSUE TITLE
An error raises when I run demo.py

### ISSUE THREAD

**Issue by shenyuan416** [zhreshold/mxnet-ssd#35]
Traceback (most recent call last):
  File "./demo.py", line 95, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "./demo.py", line 39, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/home/sheny/mxnet-ssd/symbol/symbol_vgg16_reduced.py", line 162, in get_symbol
    net = get_symbol_train(num_classes)
  File "/home/sheny/mxnet-ssd/symbol/symbol_vgg16_reduced.py", line 118, in get_symbol_train
    clip=True, interm_layer=0)
  File "/home/sheny/mxnet-ssd/symbol/common.py", line 111, in multibox_layer
    from_layer = mx.symbol.Scale(data=from_layer, mode="spatial", \
AttributeError: 'module' object has no attribute 'Scale'

**Comment by shenyuan416** [comment]
I have used git clone --recurisve to pull the entire repository, but this error still happen

**Comment by rongrongxiangxin** [comment]
I got the same error.

**Comment by shenyuan416** [comment]
I have solved this problem by using the mxnet included in mxnet-ssd, because the author add some layer such as Scale in mxnet.

**Comment by zhreshold** [comment]
Yes, you have to use the included mxnet, and make sure python import this specific lib otherwise it will fail to load special layers

**Comment by zhreshold** [comment]
@rongrongxiangxin It's not about CUDA, it's the repo you used and imported.

**Comment by rongrongxiangxin** [comment]
@shenyuan416  I also used the mxnet included in mxnet-ssd, and build to generate libmxnet.so. How to add some layer such as Scale? Thanks.

**Comment by shenyuan416** [comment]
@rongrongxiangxin You may add the environment variables to system, the special layers such as Scale have been included in mexnet-ssd/menet.
