### ISSUE TITLE
mx.symbol.Scale not found

### ISSUE THREAD

**Issue by Walid-Ahmed** [zhreshold/mxnet-ssd#38]
I installed MXNET using instructions from http://mxnet.io/get_started/osx_setup.html
with  git clone --recursive https://github.com/dmlc/mxnet

then
I used git clone --recursive https://github.com/zhreshold/mxnet-ssd.git

I still have the same error  when I try to excute demo.py
AttributeError: 'module' object has no attribute 'Scale'

I even tried 
1-git clone --recursive https://github.com/zhreshold/mxnet.git  and 
2-edit  the file tools/find_mxnet  as mentioned in [issue 11](https://github.com/zhreshold/mxnet-ssd/issues/11) 

but problem is not resolved

Thanks

**Comment by zhreshold** [comment]
You have misunderstand the structure of this project.
1. git clone --recursive zhreshold/mxnet-ssd.git
2. cd mxnet-ssd/mxnet
3. regard this mxnet as the official one. follow the official instruction. Thus you will enable some extra layers, such as Scale and MultiboxPrior...

**Comment by Walid-Ahmed** [comment]
Thanks for clarification, now I do not have this error any more

**Comment by pogilon** [comment]
@Walid-Ahmed, @zhreshold  could you please elaborate more on this? Could you please give more details about how to install the new layers using the new mxnet? I am not having any luck. Thanks

**Comment by pogilon** [comment]
@Walid-Ahmed, @zhreshold .  I was still using the original mxnet installation. Thanks! Solved!
