### ISSUE TITLE
I want to know the speed on this SSD is similar to caffe's?

### ISSUE THREAD

**Issue by AihahaFox** [zhreshold/mxnet-ssd#4]
I test this in my machine which GPU is 1080, but fps is only  around 20.

**Comment by zhreshold** [comment]
Theoretically should be very similar. What setting are you using? Batch size? cudnn enabled or not? Image processing method? These all matters.
You could refer to this issue: https://github.com/weiliu89/caffe/issues/123, there's lots of discussion.

**Comment by terrychenism** [comment]
Thanks for your great work! 
I also found the speed problem, I think it should be MultiBoxDetection layer problem. 
I have wrote the script to test the speed on TitanX, here is the result: 

without MultiBoxDetection:
{'data': (1, 3, 300, 300), 'ctx': gpu(0)} 0.0150943040848

with MultiBoxDetection:
{'data': (1, 3, 300, 300), 'ctx': gpu(0)} 0.0882755041122

You can comment this line to test on your  machine
https://github.com/terrychenism/mxnet-ssd/blob/master/mx_ssd_speed.py#L176

**Comment by AihahaFox** [comment]
@zhreshold , i enabled cudnn v5.1 and i test the speed in the demo.py, so the config is just the same, but it just have to spend around 50ms to process an image

**Comment by AihahaFox** [comment]
Thank you for your advice. Now I test the time of sorting part and apply nms part, here is the result:

sorting：18.584448(ms)
ApplyNMS：16.389791(ms)
Detection time for 1 images: 0.0523 sec

the last time is the whole time used for test one image.

**Comment by zhreshold** [comment]
Thanks for the results. 35ms for these two parts.
Currently, sorting and NMS are applied to all anchors(7000+), this could result in insufficient runtime.
Early eliminate boxes with very low score could improve the speed, but I need some time to evaluate the improvement.

**Comment by terrychenism** [comment]
@AihahaFox  could you provide the method how you test the sorting part and apply nms part?

**Comment by zhreshold** [comment]
Figured out that most time was wasted in cuda kerenel calls.
So I have rewritten the detection layer in 09cf2040f9a29787b26d6c38430bb93cd2ed86bd.
Now the forward time in this layer took me 0.0x ms

Please report the new result if possible.

**Comment by terrychenism** [comment]
forward time for detection layer on titanx: 80ms.   How you test the detection layer, in python or cpp? As I know the original code is slow mainly because of the sorting part.

**Comment by zhreshold** [comment]
@terrychenism 
I checked your measurement code, you are using random weights with random inputs, which might generate too much results. In real world scenario, only a very small portion will be used out of the 7k anchors.
You should use trained model to test.
The revised code is based on an assumption that the majority anchors will be discarded after prediction.

```
def check_speed(sym, ctx, scale=1.0, N=1000):
    exe = sym.simple_bind(grad_req='write', **ctx)
    _, arg_params, aux_params = mx.model.load_checkpoint('model/ssd_300', 0)
    # init = [np.random.normal(size=arr.shape, scale=scale) for arr in exe.arg_arrays]
    # for arr, iarr in zip(exe.arg_arrays, arg_params):
    #     arr[:] = iarr.astype(arr.dtype)
    exe.copy_params_from(arg_params, aux_params)

    exe.forward(is_train=False)
    exe.outputs[0].wait_to_read()

    tic = time.time()
    for i in range(N):
        exe.forward(is_train=False)
        exe.outputs[0].wait_to_read()
    return (time.time() - tic)*1.0/N
```
without detection:
{'data': (1, 3, 300, 300), 'ctx': gpu(0)} 0.0142086029053
w/
{'data': (1, 3, 300, 300), 'ctx': gpu(0)} 0.015056681633

Seems fine for me.

**Comment by terrychenism** [comment]
Thank you for the corrections. It works for me.

**Comment by AihahaFox** [comment]
@zt706 Thanks for your help, the problem is caused by the multiboxdetect, your speed is tested by the edited multiboxdetect.cu, the result is the same as mine
