### ISSUE TITLE
Can not download the pretrained model: ssd_300_voc_0712.zip

### ISSUE THREAD

**Issue by mychina75** [zhreshold/mxnet-ssd#40]
Are there other URL to get the model? Thanks.

**Comment by zhreshold** [comment]
Try again plz. The one is hosted on github.

**Comment by mychina75** [comment]
Thank you, but still not accessable.
Url address not change?
https://dl.dropboxusercontent.com/u/39265872/ssd_300_voc0712.zip

**Comment by zhreshold** [comment]
You might need a vpn

**Comment by xilaili** [comment]
I got the same problem. Can not download it. Can anyone share it?

**Comment by zhreshold** [comment]
Links fixed, plz try again.
