### ISSUE TITLE
(not an issue)is there a camera version?

### ISSUE THREAD

**Issue by albertyou2** [zhreshold/mxnet-ssd#43]
hi @zhreshold 
is there a camera version of  mxnet-ssd?or could mxnet-ssd be used with frames which  are captured from a camera device?if it could ,how to do it?
thank you  very much !

**Comment by zhreshold** [comment]
You can use detector.detect API, for whatever application you like, including camera

**Comment by luckydog1995** [comment]
Dear sir,I found that the parameters of the API in detector.detect was "the name of the picture".How could I deal with the raw picture came from cv2.imread.
