### ISSUE TITLE
compilation fail on TX1 - call of overloaded is ambiguous due to explicit struct

### ISSUE THREAD

**Issue by erikbeall** [zhreshold/mxnet-ssd#49]
Hi Joshua,

I ran into an issue compiling on an Nvidia Jetson TX1, with gcc-4.8.4, nvcc/CUDA v7.0, cmake 3.2.2, which seems to be due to the way a struct is defined in src/operator/<multibox_prior-inl.h, multibox_target-inl.h and multibox_detection-inl.h>. This only happens with some versions of gcc/g++, I believe because the tools have evolved in following the explicit keyword. Anyways, it was a simple fix. First, here's a (shortened) segment of my original make log output in case someone else is having the issue:

`src/operator/./multibox_prior-inl.h:114:71: error: call of overloaded ‘SizeInfo(<brace-enclosed initializer list>)’ is ambiguous`
`DECLARE_FIELD(sizes).set_default(SizeInfo({1.0f}))`
`src/operator/./multibox_prior-inl.h:114:71: note: candidates are:`
`src/operator/./multibox_prior-inl.h:42:10: note: mxnet::op::SizeInfo::SizeInfo(std::vector<float>)`
`   explicit SizeInfo(std::vector<float> in) : info(in) {}`

What worked for me (I'm not a language expert but this made sense) was to instantiate the struct following the convention enforced by the explicit keyword, like so:

`std::vector<float> InitStdVec = {0.1f, 0.1f, 0.2f, 0.2f};`
`VarInfo DefaultInitInfo = VarInfo(InitStdVec);`
`DECLARE_FIELD(sizes).set_default(DefaultInitInfo)`

This is done in each of those three header files, where DMLC_DECLARE_FIELD is setting a default for VarInfo, VarsInfo and SizeInfo. I don't know if these changes would conflict on other variants of gcc/g++, so you may not want to do anything without more user feedback.  Thank you Joshua, great work on porting SSD to mxnet!

Erik

**Comment by zhreshold** [comment]
Cuda 7.0 didn't support c++11 new features very well. Explicitly initializing vector is a solution regarding your environment.  Don't worry about it. I might modify it as well later sometime.

**Comment by erikbeall** [comment]
Thanks Joshua, seems perfectly reasonable.
