### ISSUE TITLE
Performance issues between version on official mxnet and version on mxnet-ssd

### ISSUE THREAD

**Issue by edmBernard** [zhreshold/mxnet-ssd#51]
I train a model on both version :
- the version in official repos example
- the version here

I got really bad results when I use the version in official repository
(I use exact same input parameters and datas)
Have you experience same issues ?

**Comment by zhreshold** [comment]
Could you provide more details?

**Comment by edmBernard** [comment]
I use the exact same data and configuration : 
* on your repos,  I got: 
```
INFO:root:Epoch[26] Train-Acc=0.886437
INFO:root:Epoch[26] Train-ObjectAcc=0.671642
INFO:root:Epoch[26] Train-SmoothL1=5.021330
INFO:root:Epoch[26] Time cost=2307.235
```
that was already a quite good detection 

* on mxnet/example/ssd : 
```
INFO:root:Epoch[26] Train-Acc=0.785770
INFO:root:Epoch[26] Train-ObjectAcc=0.182737
INFO:root:Epoch[26] Train-SmoothL1=20.170220
INFO:root:Epoch[26] Time cost=1794.627
...
INFO:root:Epoch[55] Train-Acc=0.782617
INFO:root:Epoch[55] Train-ObjectAcc=0.163265
INFO:root:Epoch[55] Train-SmoothL1=21.588834
INFO:root:Epoch[55] Time cost=1795.653
```

**Comment by edmBernard** [comment]
I think the issue was the convolution tuning : 
without it I already got (and it's already in ascending slope): 
```
INFO:root:Epoch[0] Batch [2780]	Speed: 32.27 samples/sec	Train-Acc=0.805153
INFO:root:Epoch[0] Batch [2780]	Speed: 32.27 samples/sec	Train-ObjectAcc=0.366649
INFO:root:Epoch[0] Batch [2780]	Speed: 32.27 samples/sec	Train-SmoothL1=15.288175
```

**Comment by zhreshold** [comment]
I see, could be something related to convolutional padding mode. I will track this.

**Comment by edmBernard** [comment]
Is it possible to convert model from your repos to official mxnet/example/ssd ?

**Comment by edmBernard** [comment]
I will try other parameters tuning, according to your answer : 
https://github.com/dmlc/mxnet/issues/4120#issuecomment-266305244

**Comment by edmBernard** [comment]
Maybe i got my mistake, on my pc the version of official repos don't use cudnn.
And it seem to work know.
