### ISSUE TITLE
How to access the coordinates of ground truth boxes in multibox_target.cu?

### ISSUE THREAD

**Issue by sjiang17** [zhreshold/mxnet-ssd#53]
Hi, I was have trouble accessing  the coordinates of ground truth boxes in multibox_target.cu.
Could you briefly explain where and how they are stored in the code? Thank you.

**Comment by zhreshold** [comment]
Ground-truth are stored in label as a batchsize * num_objects * 5 tensor, where 5 is (id, xmin, ymin, xmax, ymax)
