### ISSUE TITLE
Training SSD with a custom dataset

### ISSUE THREAD

**Issue by VanitarNordic** [zhreshold/mxnet-ssd#56]
Hello,

I have configured Caffe-SSD and download a 300 * 300 model which contains `prototxt `files and a `caffemodel`. I use DIGITS 5. it is actually a GUI for the Caffe.

I want to train this model (fine-tune) it with my own images (dataset) but I have some challenges:

- Creating LMDB files for training/validation images and labels
- Annotating images

I assume annotation should comply with COCO format maybe, which a tool that can do this annotation task is unknown for me. besides I do not know how to create those 4 LMDB files after that.

Could you help and and give some tips to do these process?

**Comment by zhreshold** [comment]
You mean how to create LMDB for custom dataset? To be honest, I'm not familiar with creating LMDB for ssd either, especially not from PASCAL-VOC formats. You best bet is to organize your own data just like pascal-voc(xml labels), and process with the code provided in caffe-ssd

**Comment by zhreshold** [comment]
This question is in-relative to this project so I will close this issue, you can send me email if hopefully I can help with. However, some issues are deeply rooted in caffe implementations, which I am trying to avoid, that's the reason I reimplemented it again.

**Comment by VanitarNordic** [comment]
May I ask your Email sir?

**Comment by zhreshold** [comment]
cheungchih at gmail

**Comment by MohammadMoradi** [comment]
Hi,
I'm trying to train SSD on my own data by DIGITS but I got the error that AnnotatedData layer is not supported in DIGITS. Did you manage to train SSD by DIGITS?
