### ISSUE TITLE
I find it takes more memory than caffe

### ISSUE THREAD

**Issue by xiaoxiong1988** [zhreshold/mxnet-ssd#57]
hi. I tried to train the ssd model using MXnet and caffe. but when I tried to deploy them, i find the caffe one needs about 1.1G memory  and the mxnet needs about 1.3G memory. (I'm using 2000 pics to check that )
I can't figure this out, cuz all the people r keep saying mxnet needs less memory than caffe. 
can u suggest which step I should check my code??
thx

**Comment by zhreshold** [comment]
What did you mean by 1.3G and 1.1G, the memory for training or testing with single image?
As far as I know, caffe-ssd uses python to compose prototxt and call executable to process, while mxnet will load the python module in memory, which might be a possible reason why it took more memory.
However, you can also configure mxnet to run from exe as well, by skipping the python interface.

**Comment by xiaoxiong1988** [comment]
oh what i mean is that when i tried to detect the image, the GPU needs about more gpu memory than caffe  python interface one. what i mention above about memory i mean GPU's  memory.  so do u mean that c++ version should take less gpu memory?cuz i wont load the python module in memory??

**Comment by zhreshold** [comment]
In terms of GPU memory, I think it doesn't matter whether it's c++/python.
I think mxnet has many parameters you can tune to reduce the gpu memory through ENVIRONMENT PARAMETERS, because mxnet has a lot of optimization and estimation that could trade-off between memory and speed.
