### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by nadiagit** [zhreshold/mxnet-ssd#59]
Hi,

I appreciate your work. Have you converted also other models provided? (e.g. 07++12+COCO: SSD300*, SSD512*). If not, can you guide me on how could I do that? 
Thank you.

**Comment by zhreshold** [comment]
I will need to update some parts to allow converted model to work for the latest caffe ssd updates. But I can't guarantee when it will be done depending on my schedule recently.

**Comment by nadiagit** [comment]
I understand, I will come back :)
