### ISSUE TITLE
Is the "dev" branch ready to use?

### ISSUE THREAD

**Issue by rorschachhb** [zhreshold/mxnet-ssd#62]
Hi, I'm trying to learn ssd and it's implementations recently, and I thought it may be better to learn from the latest code. Is the "dev" branch working now? Thanks!

**Comment by zhreshold** [comment]
It's basically runnable, but documents are messy, you will probably have a hard time trying to understand some parts.

**Comment by rorschachhb** [comment]
I'll try. Thanks.
