### ISSUE TITLE
demo.py stops with "ImportError: No module named 'imdb'"

### ISSUE THREAD

**Issue by cborelc** [zhreshold/mxnet-ssd#63]
Hi:
I was able to follow the instructions and build mxnet-ssd. I built it on Windows 10 using Anaconda with "activate py35". But now when I run the demo.py example I get:

(py35) F:\programs\mxnet-ssd\mxnet-ssd>python demo.py --epoch 0 --images ./data/demo/dog.jpg --thresh 0.5
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    from detect.detector import Detector
  File "F:\programs\mxnet-ssd\mxnet-ssd\detect\detector.py", line 4, in <module>
    from dataset.testdb import TestDB
  File "F:\programs\mxnet-ssd\mxnet-ssd\dataset\testdb.py", line 2, in <module>
    from imdb import Imdb
ImportError: No module named 'imdb'

I see there is a imdb.py file in dataset. I tried to google the error but could not find anything that solved the problem.
Thanks

**Comment by zhreshold** [comment]
I would suggest making sure there's a __init__.py in folder dataset, or perhaps you have edited it, so there's invisible characters inside that file.

**Comment by MyAusweis** [comment]
Dear 
I have the same problem with you, _init_.py available, and i never edited this file

Thx

**Comment by AlexDag** [comment]
change "from imdb import Imdb" by "from dataset/imdb import Imdb"

**Comment by gkbell46** [comment]
change "from imdb import Imdb" to "from dataset.imdb import Imdb"

**Comment by zhreshold** [comment]
Should be fixed now
