### ISSUE TITLE
fail to prepare dataset.

### ISSUE THREAD

**Issue by nopattern** [zhreshold/mxnet-ssd#66]
Congratulations for new release!
  I failed to prepare dataset by command :
 `python tools/prepare_dataset.py --dataset pascal --year 2007,2012 --set trainval --target ./data/train.lst`
   
  The output is 

> List file ./data/train.lst generated...
Creating .rec file from /home/deep/work/mxnet-ssd/data/train.lst in /home/deep/work/mxnet-ssd/data
multiprocessing not available, fall back to single threaded encoding
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/deep/work/opencv-3.1.0/modules/core/src/matrix.cpp, line 1879
Traceback (most recent call last):
  File "/home/deep/work/mxnet-ssd/tools/../mxnet/tools/im2rec.py", line 118, in image_encode
    img = cv2.imread(fullpath, args.color)
error: /home/deep/work/opencv-3.1.0/modules/core/src/matrix.cpp:1879: error: (-213) Unknown/unsupported array type in function type

> imread error trying to load file: /home/deep/work/mxnet-ssd/data/VOCdevkit/VOC2012/JPEGImages/2008_001814.jpg 
> Traceback (most recent call last):
>   File "/home/deep/work/mxnet-ssd/tools/../mxnet/tools/im2rec.py", line 296, in <module>
>     record.write_idx(item[0], s)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/recordio.py", line 162, in write_idx
>     self.write(buf)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/recordio.py", line 78, in write
>     ctypes.c_size_t(len(buf))))
> TypeError: object of type 'NoneType' has no len()
> Traceback (most recent call last):
>   File "tools/prepare_dataset.py", line 81, in <module>
>     "--shuffle", str(int(args.shuffle)), "--pack-label", "1"])
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['python', '/home/deep/work/mxnet-ssd/tools/../mxnet/tools/im2rec.py', '/home/deep/work/mxnet-ssd/data/train.lst', '/home/deep/work/mxnet-ssd/data/VOCdevkit', '--shuffle', '1', '--pack-label', '1']' returned non-zero exit status 1

 
 I have checked the jpeg file which is right.

**Comment by nopattern** [comment]
Problem solved by moving 'import cv2' to head. Why?

**Comment by zhreshold** [comment]
Do you have multiple versions of opencv?

**Comment by nopattern** [comment]
yes ,that may be the problem .

**Comment by JerrySor** [comment]
@nopattern : you said " Problem solved by moving 'import cv2' to file head. Why?" 
 so could you advice me how to do please!
