### ISSUE TITLE
pixi

### ISSUE THREAD

**Issue by siyiding1216** [zhreshold/mxnet-ssd#67]
I have below error when building. Do you know what is missing?
/usr/bin/ld: cannot find -lippicv
collect2: error: ld returned 1 exit status

**Comment by zhreshold** [comment]
https://github.com/dmlc/mxnet/issues/1816
Check if you have the opencv installed correctly

**Comment by siyiding1216** [comment]
Thanks. Link the opencv lib did not help, but recompile opencv and install helped.
