### ISSUE TITLE
'Module' object has no attribute 'MultiBoxPrior'

### ISSUE THREAD

**Issue by lvaleriu** [zhreshold/mxnet-ssd#68]
When i build the official mxnet sources (latest master) and try to run the demo script in the ssd example, i cannot use the contrib symbols. Have you experienced such thing? Should i better use the mxnet version from your submodules repository?

**Comment by zhreshold** [comment]
You better use the submodule cuz I havn''t submitted PR to official repo yet.

**Comment by lvaleriu** [comment]
It works better now. Strange.
