### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by biycyr** [zhreshold/mxnet-ssd#71]
I get below error message when I try to run demo.py

> [18:19:45] src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Detection time for 1 images: 0.0986 sec
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/ycliu/opencv/modules/core/src/matrix.cpp, line 1962
Traceback (most recent call last):
  File "demo.py", line 102, in <module>
    CLASSES, args.thresh, args.show_timer)
  File "/home/ycliu/mxnet-ssd/detect/detector.py", line 171, in detect_and_visualize
    img = cv2.imread(im_list[k])
cv2.error: /home/ycliu/opencv/modules/core/src/matrix.cpp:1962: error: (-213) Unknown/unsupported array type in function type

 `cv2.__version__` shows that my opencv version is 2.4.8. I use python2.7

Does anyone has similar problem?

**Comment by nopattern** [comment]
This may be caused by there are more than one versions of opencv in you enviroment.[https://github.com/zhreshold/mxnet-ssd/issues/66](url)

**Comment by BenLag2906** [comment]
hi,
I have a similar problem :
version 2.4.9.1
OpenCV Error: Assertion failed (channels() == CV_MAT_CN(dtype)) in copyTo, file /home/esi/open-last/opencv-master/modules/core/src/copy.cpp, line 259
Traceback (most recent call last):
  File "/home/esi/deep/mxnet-ssd/tools/../mxnet/tools/im2rec.py", line 293, in <module>
    image_encode(args, i, item, q_out)
  File "/home/esi/deep/mxnet-ssd/tools/../mxnet/tools/im2rec.py", line 117, in image_encode
    img = cv2.imread("/home/esi/deep/mxnet-ssd/data/VOCdevkit/VOC2007/JPEGImages/001962.jpg")

Python version is 2.7.

Morevover when I execute the cv2.read function in a single script, it works.
Any Idea ?

**Comment by biycyr** [comment]
> This may be caused by there are more than one versions of opencv in you 
> enviroment.https://github.com/zhreshold/mxnet-ssd/issues/66
The page of issues 66 is missing. However, I do have to versions of opencv in my computer, 2.4.8 for python2 and 3.2.0 for python3.
I still do not know what causes this problem. However, I find a way to work around. I use ipython and type
`import cv2` 
then
`%run demo.py`

and it works. It seems that I have messed up my path setting.
