### ISSUE TITLE
slow than caffe

### ISSUE THREAD

**Issue by anguoyang** [zhreshold/mxnet-ssd#72]
when i test on the street.jpg, it took about 18 seconds! only for detection.
however, when i use the same image testing on caffe, it took about 10 seconds.
they are all in the cpu mode.

**Comment by zhreshold** [comment]
Check the mxnet cpu worker configuration: MXNET_CPU_WORKER_NTHREADS, by default it's 1, means you are using single thread to run.

**Comment by anguoyang** [comment]
您好，非常感谢！另外，我还想问一下。我在GPU模式也测试了一下，大约需要400毫秒，还是有点慢，是有类似的配置么？多谢多谢！

**Comment by anguoyang** [comment]
gpu为1060
