### ISSUE TITLE
Training speed slows down

### ISSUE THREAD

**Issue by Jinwoo-Jeon** [zhreshold/mxnet-ssd#75]
Hi. Thanks for sharing this great work.
I have a question about the training speed (with custom dataset).
I'm trying to train ssd model with your train.py code.

At first, training speed was fast, but after a few epochs it slowed down sharply.

Here is my training log.

```
Epoch[0] Batch [20]	Speed: 95.71 samples/sec	Train-CrossEntropy=3.167187
Epoch[0] Batch [20]	Speed: 95.71 samples/sec	Train-SmoothL1=0.744193
Epoch[0] Batch [40]	Speed: 94.49 samples/sec	Train-CrossEntropy=2.297927
Epoch[0] Batch [40]	Speed: 94.49 samples/sec	Train-SmoothL1=0.683903

....

Epoch[60] Batch [60]	Speed: 94.29 samples/sec	Train-CrossEntropy=0.623047
Epoch[60] Batch [60]	Speed: 94.29 samples/sec	Train-SmoothL1=0.245183
Epoch[60] Batch [80]	Speed: 90.31 samples/sec	Train-CrossEntropy=0.624128
Epoch[60] Batch [80]	Speed: 90.31 samples/sec	Train-SmoothL1=0.239627
Epoch[60] Batch [100]	Speed: 89.77 samples/sec	Train-CrossEntropy=0.625347
Epoch[60] Batch [100]	Speed: 89.77 samples/sec	Train-SmoothL1=0.243057

...

Epoch[61] Batch [20]	Speed: 97.99 samples/sec	Train-CrossEntropy=0.626057
Epoch[61] Batch [20]	Speed: 97.99 samples/sec	Train-SmoothL1=0.245972
Epoch[61] Batch [40]	Speed: 46.48 samples/sec	Train-CrossEntropy=0.631146
Epoch[61] Batch [40]	Speed: 46.48 samples/sec	Train-SmoothL1=0.246695
Epoch[61] Batch [60]	Speed: 23.47 samples/sec	Train-CrossEntropy=0.624462
Epoch[61] Batch [60]	Speed: 23.47 samples/sec	Train-SmoothL1=0.245014
Epoch[61] Batch [80]	Speed: 22.42 samples/sec	Train-CrossEntropy=0.624129
Epoch[61] Batch [80]	Speed: 22.42 samples/sec	Train-SmoothL1=0.242894

...

Epoch[97] Batch [20]	Speed: 28.98 samples/sec	Train-CrossEntropy=0.572588
Epoch[97] Batch [20]	Speed: 28.98 samples/sec	Train-SmoothL1=0.221427
Epoch[97] Batch [40]	Speed: 20.40 samples/sec	Train-CrossEntropy=0.560714
Epoch[97] Batch [40]	Speed: 20.40 samples/sec	Train-SmoothL1=0.214364
Epoch[97] Batch [60]	Speed: 19.32 samples/sec	Train-CrossEntropy=0.560793
Epoch[97] Batch [60]	Speed: 19.32 samples/sec	Train-SmoothL1=0.212174
Epoch[97] Batch [80]	Speed: 22.78 samples/sec	Train-CrossEntropy=0.568777
Epoch[97] Batch [80]	Speed: 22.78 samples/sec	Train-SmoothL1=0.215357
Epoch[97] Batch [100]	Speed: 25.34 samples/sec	Train-CrossEntropy=0.562203
Epoch[97] Batch [100]	Speed: 25.34 samples/sec	Train-SmoothL1=0.213804
```

I'm using TITAN X (MAXWELL) x3 for training, and here is my training command.

python train.py --train-path ./data/my_train.rec --val-path ./data/my_val.rec \
--batch-size 128 --gpus 0,1,2 --lr 0.001

Have you ever experienced this issue?

**Comment by Jinwoo-Jeon** [comment]
Interestingly, the training speed comes back when I resume training with --resume xxx arg.
But eventually training speed drops again. 
I checked nobody elses use gpu during training.

**Comment by zhreshold** [comment]
I once had a similar problem, but was with image-classification, so I suspect that might be something related to mxnet engine. However, I just can't reproduce it, for most time it just works fine. Also you cannot assert that it's 100% software part, since gpu might overheat or switch power state.

It's rather complicated, so I suggest you can post a issue on official mxnet, see if others have same problems as well.

**Comment by Jinwoo-Jeon** [comment]
@zhreshold 
Thanks for reply.
I think until this issue solved, I should stop and resume when training speed drops .
