### ISSUE TITLE
demo.py - AttributeError: 'module' object has no attribute 'Constant'

### ISSUE THREAD

**Issue by yash1** [zhreshold/mxnet-ssd#77]
Hi, 

I am trying to run 'python demo.py', but I'm getting an AttributeError. Any ideas why?

> _Traceback (most recent call last):
>   File "demo.py", line 99, in <module>
>     ctx, args.nms_thresh, args.force_nms)
>   File "demo.py", line 40, in get_detector
>     .get_symbol(len(CLASSES), nms_thresh, force_nms)
>   File "/home/ubuntu/mxnet-ssd/symbol/symbol_vgg16_ssd_300.py", line 179, in get_symbol
>     net = get_symbol_train(num_classes)
>   File "/home/ubuntu/mxnet-ssd/symbol/symbol_vgg16_ssd_300.py", line 100, in get_symbol_train
>     stride=(1,1), act_type="relu", use_batchnorm=False)
>   File "/home/ubuntu/mxnet-ssd/symbol/common.py", line 34, in conv_act_layer
>     init=mx.init.Constant(0.0), attr={'__lr_mult__': '2.0'})
> AttributeError: 'module' object has no attribute 'Constant'_

**Comment by zhreshold** [comment]
Update submodule and recompile again

**Comment by yash1** [comment]
Thanks, that fixed it
