### ISSUE TITLE
any instructions for training on custom dataset?

### ISSUE THREAD

**Issue by albertyou2** [zhreshold/mxnet-ssd#79]
@zhreshold 
is any instructions for training on custom dataset step by step?
thank you !

**Comment by zhreshold** [comment]
1. Create the parser for custom dataset as subclass of dataset/imdb.Imdb(), implement all the virtual functions, you can refer to pascal and yolo examples in the same folder.
2. In tools/prepare_dataset.py, add you new dataset
3. Run tools/prepare_dataset.py to get your record file, and load that one in train.py

**Comment by albertyou2** [comment]
thanks .I got it
