### ISSUE TITLE
Fine Tuning 

### ISSUE THREAD

**Issue by moh3th1** [zhreshold/mxnet-ssd#8]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by zhreshold** [comment]
First, implement the dataset as a subclass of dataset.Imdb.
Then checkout the --finetune option. In this mode, all convolutional feature layers will be fixed except box prediction layers.

**Comment by amlarraz** [comment]
Me too! Can you explain how add the dataset? I'm trying but i have some diferent errors

**Comment by zhreshold** [comment]
Two examples available: dataset/pascal_voc.py and dataset/yolo_format.py

**Comment by ChristineRYY** [comment]
i have this question
