### ISSUE TITLE
Question about train image size

### ISSUE THREAD

**Issue by niluanwudidadi** [zhreshold/mxnet-ssd#81]
Hello, @zhreshold ,I have used my own trainset  to train , my image size is (3,1280,200). I want to know which parameter works best, can you tell me some skills for tuning。Thank you very much.

**Comment by zhreshold** [comment]
You image is too wide, which won't work for ssd as it will resize to 300x300, then the image is distorted quite a bit. 
I would cut the image into several parts and train use default parameters should be fine.

**Comment by niluanwudidadi** [comment]
Thanks for your reply! It can detect character in the image without cutting the image, but if the character is too close, it will appear reapeat box. In my own dataset, if I cut the image,may be some character will be cut,it will affect the performance.So, do you have any other suggestions?Thank you very much . @zhreshold

**Comment by zhreshold** [comment]
I would try different aspect ratio other than 1:1 and train a new model for the specific usage

**Comment by niluanwudidadi** [comment]
Thank you very much！ @zhreshold

**Comment by niluanwudidadi** [comment]
Hi, @zhreshold I have met a problem , when I run demo.py for one hundred images, it takes 45ms in average,but when I run demo.py image by image ,it takes 180ms per image. Is there is a solution for this?

**Comment by zhreshold** [comment]
It is normal because each time it will load the network and parameters when you enter demo..py
Solution is to keep the detector, and call detect_and_visualize each time when you want to detect new images.

**Comment by niluanwudidadi** [comment]
Yes,I have done like you says. Each time call detect_and_visualize, I have locate the problem, in detector.py, the code **"detections = self.mod.predict(det_iter, reset=False).asnumpy()"**, I have found foward only take 10ms, but asnumpy() take around 100ms, I want to know the reason ,can you give me a  solution? @zhreshold

**Comment by zhreshold** [comment]
I think forward time is not accurate because the process is asynchrous until you call the asnumpy(). 
Launching executor takes time, so I think it's reasonable.

**Comment by niluanwudidadi** [comment]
Thank you very much! @zhreshold 
I have now used ssd for real-time detection, now I have met a few questions:
**1.**when I call im_detect image by image, then  python generate too many threads and continue increase, which cause slow speed, how can we solve this problem?
**2.**when I use vgg_ssd_512 network and 512 data-shape, detcection cost 150ms around image by image, and then I make predict parameter reset=False, it cost 100ms around , but I want more improvement, reduce more time for the real-time detection, is there any solutions?

**Comment by zhreshold** [comment]
I suppose there is somewhere speed up can happen, but you need to figure out the bottleneck
