### ISSUE TITLE
Metric error on the last version of ssd

### ISSUE THREAD

**Issue by edmBernard** [zhreshold/mxnet-ssd#84]
On the last version of ssd (I don't know since when)
I got this error when I try to train with all default parameters on pascal voc : 
```
[18:45:00] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/home/rd/Documents/RD3/users/Hinde/mxnet/example/ssd/train/train_net.py", line 266, in train_net
    monitor=monitor)
  File "/home/rd/Documents/RD3/lib/mxnet/python/mxnet/module/base_module.py", line 481, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/rd/Documents/RD3/lib/mxnet/python/mxnet/module/module.py", line 664, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/rd/Documents/RD3/lib/mxnet/python/mxnet/module/executor_group.py", line 558, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/rd/Documents/RD3/lib/mxnet/python/mxnet/metric.py", line 82, in update_dict
    pred = [pred[name] for name in self.output_names]
TypeError: 'int' object is not iterable
```

The problem seem to come from prediction that return an index instead a list of index.
I use mxnet 0.9.5 and cudnn 6. 
edit : I use ssd code from official mxnet repository (mxnet/example/ssd)

**Comment by zhreshold** [comment]
Can you figure out what self.output_names is in your case?

**Comment by edmBernard** [comment]
2

**Comment by zhreshold** [comment]
so i guess that means something broken in the python module in the latest version

**Comment by edmBernard** [comment]
yeah probably, something in the metric part

**Comment by erikbeall** [comment]
The initialization of EvalMetric (mxnet/python/mxnet/metric.py) has changed, previously (and what is assumed now in mxnet-ssd/train/metric.py) the initialization was:
`__init__(self, name, num=None):`

and it was sufficient to intialize with name, num. The init of this on line 8 of train/metric.py reads:
`super(MultiBoxMetric, self).__init__(['CrossEntropy', 'SmoothL1'], 2)`

However, EvalMetric's init has changed to
`__init__(self, name, output_names=None, label_names=None, **kwargs):`

I changed line 8 of train/metric.py to:
`super(MultiBoxMetric, self).__init__(name=['CrossEntropy', 'SmoothL1'],output_names=['cls_prob_output', 'loc_loss_output', 'cls_label_output','det_out_output'])`
and added a `self.num=2` data member in MultiBoxMetric. However, because there isn't a self.num member in EvalMetric, it doesn't handle evaluations along more than one axis, so I hacked EvalMetric in ::reset(), changing the resetting to:
```
self.num_inst=numpy.asarray((0,0))
self.sum_metric=numpy.asarray((0.0,0.0))
```

That ugly hack needs to be fixed, but I don't know what makes the most sense, these changes were made in [b005306064369528d1295687326eb41ecc481251](https://github.com/dmlc/mxnet/commit/b005306064369528d1295687326eb41ecc481251#diff-32ef9198e6c505144c57507549cea14b) to prepare for nn, so there may be a good reason why sum_metric and num_inst were changed in this way. Do you have further insight into the right way to fix
 this?

**Comment by erikbeall** [comment]
Failed to mention, the evaluation metric that gets evaluated on each full pass must also be modified, class MApMetric in evaluate/eval_metric.py, so the initialization is like so:
`       if class_names is None:
            super(MApMetric, self).__init__(name="mAP",output_names=['cls_prob_output', 'loc_loss_output', 'cls_label_output','det_out_output'])
            self.num=1
            #super(MApMetric, self).__init__("mAP")
        else:
            assert isinstance(class_names, list)
            for name in class_names:
                assert isinstance(name, str), "must provide names as str"
            num = len(class_names)
            #super(MApMetric, self).__init__(class_names + ["mAP"], num + 1)
            super(MApMetric, self).__init__(class_names + ["mAP"], output_names=['cls_prob_output', 'loc_loss_output', 'cls_label_output','det_out_output'])
            self.num=len(class_names)
        self.sum_metric=np.asarray((0.0,0.0))
        self.num_inst=np.asarray((0,0))`

**Comment by zhreshold** [comment]
Working on pulling latest mxnet, hang tight.

**Comment by erikbeall** [comment]
Thanks @zhreshold, will hold on for now.

**Comment by devaib** [comment]
@erikbeall Thanks for the work around.

**Comment by erikbeall** [comment]
@devaib, I recommend waiting for Joshua's work integrating with latest mxnet, I was not able to validate my workarounds, getting nan's after the first iteration when training on vocdevkit.

**Comment by zhreshold** [comment]
Should be fine now with latest dmlc/mxnet, and mxnet-ssd dev branch.

**Comment by ogail** [comment]
@zhreshold I just pulled latest from dmlc/mxnet master branch, built mxnet and still getting same error
```
[22:38:58] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/home/ubuntu/ogail-efs/asin-segmentation-ssd/train/train_net.py", line 263, in train_net
    allow_missing=True,
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/base_module.py", line 495, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/module.py", line 680, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/executor_group.py", line 561, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/metric.py", line 82, in update_dict
    pred = [pred[name] for name in self.output_names]
TypeError: 'int' object is not iterable
```

**Comment by ogail** [comment]
@zhreshold the error is fixed, however I am still getting
```
This convolution is not supported by cudnn, MXNET convolution is applied
```

Is that normal?

**Comment by zhreshold** [comment]
@ogail this is normal

**Comment by erikbeall** [comment]
@zhreshold thank you for the fast updates. I confirm I get mAP of 0.7763 with VOCdevkit in unmodified evaluate.py on your v0.5-beta ssd_300 release network with stock mxnet commit a98e502b35b841a9e4a83b008dfd381a8b62b0fb (pulled at June 15th, 20:00 UTC or so).

**Comment by BunnyShan** [comment]
@erikbeall Have you tried to train voc with the latest ssd version by yourself? I only got 0.65 mAP and want to make sure it is my bad or not.

**Comment by edmBernard** [comment]
I think the initial question is fix. 
@zhreshold thanks for your work

**Comment by erikbeall** [comment]
I could only reach 0.72mAP, I've experienced inconsistencies in training performance similar to this before, and the setup can play a role. What is your setup? I'm using stock SSD/mxnet (June 30th commit d79488a17c94318b2bdacefe42d93cca514a3d92), CUDA 8.0, CUDNN 6.0, NVidia driver version 375.66, using batch sizes ranging from 20 to 48 and a range of decreasing learning rates on a Tesla K80 with stock VOCdevkit 07+12. @zhreshold are you using the train.py script as-is? Could you post your training setup?

**Comment by edmBernard** [comment]
@zhreshold I just got the same error On a personnal project. Can you explain where it come from and how did you solve it.

**Comment by BunnyShan** [comment]
@edmBernard update mxnet will solve this.
@erikbeall Yes, after make lr 0.002 I got 0.72mAP too and trying to modify other setups.
