### ISSUE TITLE
Does the latest ssd sample negatives from images where there is no ground truth?

### ISSUE THREAD

**Issue by KeyKy** [zhreshold/mxnet-ssd#89]
Hi! @zhreshold 
Does the latest ssd sample negatives anchors from images where there is no ground truth?

Thanks!

**Comment by zhreshold** [comment]
If you mean negative anchors where background reside, yes. However, it will discard image with 0 object.

**Comment by KeyKy** [comment]
@zhreshold I saw the iter_image_det_recordio.cc and found it is too hard for me to understand. Could you some an easy way to get DetIter back? I don't want to use DetRecordIter. My data have lots of 0 object images. I will modify ssd and let it accepts image with 0 object which just take all anchors as negatives. Thanks!

**Comment by KeyKy** [comment]
It was a hard time for me to modify iter_image_det_recordio.cc and let it accept 0 object images. And then i modified multibox_target.cu to random pick the negatives.
