### ISSUE TITLE
Problems converting .caffemodel

### ISSUE THREAD

**Issue by riqui99** [zhreshold/mxnet-ssd#92]
Hello first of all sorry for my english.
I tried to convert from official ssd(weiliu89/caffe) .caffemodel of COCO (https://drive.google.com/file/d/0BzKzrI_SkD1_NDlVeFJDc2tIU1k/view) when I run 

`python convert_model.py SSD_300x300/deploy.prototxt SSD_300x300/VGG_coco_SSD_300x300_iter_400000.caffemodel ssd_converted`
I recieved this error:
```
F0614 13:55:09.141768  5286 io.cpp:45] Check failed: fd != -1 (-1 vs. -1) File not found: data/coco/labelmap_coco.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
```

maybe the problem is that when I run make previously, this return :
`caffe_parse/caffe_pb2.py
from: can't read /var/mail/google.protobuf.internal
from: can't read /var/mail/google.protobuf
from: can't read /var/mail/google.protobuf
from: can't read /var/mail/google.protobuf
from: can't read /var/mail/google.protobuf
caffe_parse/caffe_pb2.py: 14: caffe_parse/caffe_pb2.py: Syntax error: "(" unexpected
Makefile:12: recipe for target 'all' failed
make: *** [all] Error 2
`

Do you have any idea to how to convert .caffemodel without problems?

Thanks!!

**Comment by riqui99** [comment]
sorry I resolve the problem.. I only need to add the "data/coco/labelmap_coco.prototxt" file into /mxnet-ssd/tools

**Comment by riqui99** [comment]
any way, I can create .json and .params files from .caffemodel but when execute the detector it fails and return 
```
[15:04:59] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
Traceback (most recent call last):
  File "demo.py", line 103, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 45, in get_detector
    data_shape, mean_pixels, ctx=ctx)
  File "/home/vintra/PycharmProjects/mxnet-ssd/detect/detector.py", line 40, in __init__
    self.mod.set_params(args, auxs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 309, in set_params
    allow_missing=allow_missing, force_init=force_init)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 274, in init_params
    _impl(desc, arr, arg_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 265, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: relu7_cls_pred_conv_bias is not presented

```

I assume that the official caffe models are not compatible with your parse, right? or I did something wrong?

Thanks!

**Comment by zhreshold** [comment]
and --deply as well
