### ISSUE TITLE
Question about mean_pixels

### ISSUE THREAD

**Issue by niluanwudidadi** [zhreshold/mxnet-ssd#94]
I wonder to know how much the mean_pixels' value is appropriate, I have seen the default is (123,117,104), when I use my own datasets, shuold I compute the mean value of all my pictures? I want to know the effect of mean_pixels and the  significance. Thank you very much!  @zhreshold

**Comment by zhreshold** [comment]
Should be fine if your data is still natural images.

**Comment by niluanwudidadi** [comment]
Thank you! @zhreshold
