### ISSUE TITLE
how to Build MXNet under windows? the official instructions link is unavailable

### ISSUE THREAD

**Issue by lankuohsing** [zhreshold/mxnet-ssd#95]
I download your repository of mxnet-ssd under windows. I met the error "MXNetError: Cannot find argument 'pooling_convention' when I ran the demo, Possible Arguments:". I guess the cause is that I didn't Build MXNet correctly because the link of the official instructions is unavailable. I

**Comment by edmBernard** [comment]
prebuild mxnet library are available here : 
https://github.com/yajiedesign/mxnet/releases
I don't know if it's compatible with @zhreshold mxnet version. But you can use SSD code in official mxnet repository : mxnet/example/ssd.

**Comment by zhreshold** [comment]
Use pip install mxnet should be good enough now.
